/*
Navicat MySQL Data Transfer

Source Server         : test
Source Server Version : 50729
Source Host           : localhost:3306
Source Database       : testdata

Target Server Type    : MYSQL
Target Server Version : 50729
File Encoding         : 65001

Date: 2021-11-18 15:57:57
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for book
-- ----------------------------
DROP TABLE IF EXISTS `book`;
CREATE TABLE `book` (
  `id` int(255) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `master` varchar(255) NOT NULL,
  `book` varchar(255) NOT NULL,
  `introduction` longtext,
  `content` longtext,
  `picture` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=570 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of book
-- ----------------------------
INSERT INTO `book` VALUES ('1', '数据结构与算法\r\n', '胡翔云\r\n', '[1]严蔚敏等. 数据结构(C语言版). 清华大学出版社. 2011.\r\n', '《数据结构（C语言版）/清华大学计算机系列教材》是为“数据结构”课程编写的教材，也可作为学习数据结构及其算法的c程序设计的参考教材。\r\n　　《数据结构（C语言版）/清华大学计算机系列教材》的前半部分从抽象数据类型的角度讨论各种基本类型的数据结构及其应用；后半部分主要讨论查找和排序的各种实现方法及其综合分析比较。其内容和章节编排与1992年4月出版的《数据结构》（第二版）基本一致，但在《数据结构（C语言版）/清华大学计算机系列教材》中更突出了抽象数据类型的概念。全书采用类C语言作为数据结构和算法的描述语言。\r\n　　《数据结构（C语言版）/清华大学计算机系列教材》概念表述严谨，逻辑推理严密，语言精炼，用词达意，并有配套出版的《数据结构题集》（c语言版），既便于教学，又便于自学。\r\n　　《数据结构（C语言版）/清华大学计算机系列教材》可作为计算机类专业或信息类相关专业的本科或专科教材，也可供从事计算机工程与应用工作的科技工作者参考。', '第1章 绪论\r\n1．1 什么是数据结构\r\n1．2 基本概念和术语\r\n1．3 抽象数据类型的表示与实现\r\n1．4 算法和算法分析\r\n1．4．1 算法\r\n1．4．2 算法设计的要求\r\n1．4．3 算法效率的度量\r\n1．4．4 算法的存储空间需求\r\n\r\n第2章 线性表\r\n2．1 线性表的类型定义\r\n2．2 线性表的顺序表示和实现\r\n2．3 线性表的链式表示和实现\r\n2．3．1 线性链表\r\n2．3．2 循环链表\r\n2．3．3 双向链表\r\n2．4 一元多项式的表示及相加\r\n\r\n第3章 栈和队列\r\n3．1 栈\r\n3．1．1 抽象数据类型栈的定义\r\n3．1．2 栈的表示和实现\r\n3．2 栈的应用举例\r\n3．2．1 数制转换\r\n3．2．2 括号匹配的检验\r\n3．2．3 行编辑程序\r\n3．2．4 迷宫求解\r\n3．2．5 表达式求值\r\n3．3 栈与递归的实现\r\n3．4 队列\r\n3．4．1 抽象数据类型队列的定义\r\n3．4．2 链队列——队列的链式表示和实现\r\n3．4．3 循环队列——队列的顺序表示和实现\r\n3．5 离散事件模拟\r\n\r\n第4章 串\r\n4．1 串类型的定义\r\n4．2 串的表示和实现\r\n4．2．1 定长顺序存储表示\r\n4．2．2 堆分配存储表示\r\n4．2．3 串的块链存储表示\r\n4．3 串的模式匹配算法\r\n4．3．1 求子串位置的定位函数Index（S，T，pos）\r\n4．3．2 模式匹配的一种改进算法\r\n4．4 串操作应用举例\r\n4．4．1 文本编辑\r\n4．4．2 建立词索引表\r\n\r\n第5章 数组和广义表\r\n5．1 数组的定义\r\n5．2 数组的顺序表示和实现\r\n5．3 矩阵的压缩存储\r\n5．3．1 特殊矩阵\r\n5．3．2 稀疏矩阵\r\n5．4 广义表的定义\r\n5．5 广义表的存储结构\r\n5．6 m元多项式的表示\r\n5．7 广义表的递归算法\r\n5．7．1 求广义表的深度\r\n5．7．2 复制广义表\r\n5．7．3 建立广义表的存储结构\r\n\r\n第6章 树和二叉树\r\n6．1 树的定义和基本术语\r\n6．2 二叉树\r\n6．2．1 二叉树的定义\r\n6．2．2 二叉树的性质\r\n6．2．3 二叉树的存储结构\r\n6．3 遍历二叉树和线索二叉树\r\n6．3．1 遍历二叉树\r\n6．3．2 线索二叉树\r\n6．4 树和森林\r\n6．4．1 树的存储结构\r\n6．4．2 森林与二叉树的转换\r\n6．4．3 树和森林的遍历\r\n6．5 树与等价问题\r\n6．6 赫夫曼树及其应用\r\n6．6．1 最优二叉树（赫夫曼树）\r\n6．6．2 赫夫曼编码\r\n6．7 回溯法与树的遍历\r\n6．8 树的计数\r\n\r\n第7章 图\r\n7．1 图的定义和术语\r\n7．2 图的存储结构\r\n7．2．1 数组表示法\r\n7．2．2 邻接表\r\n7．2．3 十字链表\r\n7．2．4 邻接多重表\r\n7．3 图的遍历\r\n7．3．1 深度优先搜索\r\n7．3．2 广度优先搜索\r\n7．4 图的连通性问题\r\n7．4．1 无向图的连通分量和生成树\r\n7．4．2 有向图的强连通分量\r\n7．4．3 最小生成树\r\n7．4．4 关节点和重连通分量\r\n7．5 有向无环图及其应用\r\n7．5．1 拓扑排序\r\n7．5．2 关键路径\r\n7．6 最短路径\r\n7．6．1 从某个源点到其余各顶点的最短路径\r\n7．6．2 每一对顶点之间的最短路径\r\n\r\n第8章 动态存储管理\r\n8．1 概述\r\n8．2 可利用空间表及分配方法\r\n8．3 边界标识法\r\n8．3．1 可利用空间表的结构\r\n8．3．2 分配算法\r\n8．3．3 回收算法\r\n8．4 伙伴系统\r\n8．4．1 可利用空间表的结构\r\n8．4．2 分配算法\r\n8．4．3 回收算法\r\n8．5 无用单元收集\r\n8．6 存储紧缩\r\n\r\n第9章 查找\r\n9．1 静态查找表\r\n9．1．1 顺序表的查找\r\n9．1．2 有序表的查找\r\n9．1．3 静态树表的查找\r\n9．1．4 索引顺序表的查找\r\n9．2 动态查找表\r\n9．2．1 二叉排序树和平衡二叉树\r\n9．2．2 B树和B+树\r\n9．2．3 键树\r\n9．3 哈希表\r\n9．3．1 什么是哈希表\r\n9．3．2 哈希函数的构造方法\r\n9．3．3 处理冲突的方法\r\n9．3．4 哈希表的查找及其分析\r\n\r\n第10章 内部排序\r\n10．1 概述\r\n10．2 插入排序\r\n10．2．1 直接插入排序\r\n10．2．2 其他插入排序\r\n10．2．3 希尔排序\r\n10．3 快速排序\r\n10．4 选择排序\r\n10．4．1 简单选择排序\r\n10．4．2 树形选择排序\r\n10．4．3 堆排序\r\n10．5 归并排序\r\n10．6 基数排序\r\n10．6．1 多关键字的排序\r\n10．6．2 链式基数排序\r\n10．7 各种内部排序方法的比较讨论\r\n\r\n第11章 外部排序\r\n11．1 外存信息的存取\r\n11．2 外部排序的方法\r\n11．3 多路平衡归并的实现\r\n11．4 置换一选择排序\r\n11．5 最佳归并树\r\n\r\n第12章 文件\r\n12．1 有关文件的基本概念\r\n12．2 顺序文件\r\n12．3 索引文件\r\n12．4 ISAM文件和VSAM文件\r\n12．4．1 ISAM文件\r\n12．4．2 VSAM文件\r\n12．5 直接存取文件（散列文件）\r\n12．6 多关键字文件\r\n12．6．1 多重表文件\r\n12．6．2 倒排文件\r\n\r\n附录A 名词索引\r\n附录B 函数索引\r\n\r\n参考书目', 'shuju');
INSERT INTO `book` VALUES ('2', '数据结构与算法', '胡翔云', '[2]李春葆. 数据结构教程(第4版). 清华大学出版社. 2013.', null, null, null);
INSERT INTO `book` VALUES ('3', '数据结构与算法', '胡翔云', '[3]殷人昆. 数据结构(用面向对象方法与C++语言描述)第二版. 清华大学出版社. 2007.', null, null, null);
INSERT INTO `book` VALUES ('4', '遥感物理基础', '石文轩', '[1]谢处方,饶克谨. 电磁场与电磁波(第4版). 高等教育出版社. 2006.', null, null, null);
INSERT INTO `book` VALUES ('5', '遥感物理基础', '石文轩', '[2] W.G.Rees. Physical Principles of Remote Sensing, Second Edition. Cambridge University Press. 2001.', null, null, null);
INSERT INTO `book` VALUES ('6', '遥感物理基础', '石文轩', '[3]吕斯骅. 遥感物理基础[M]. 商务印书馆出版社, 1981.', null, null, null);
INSERT INTO `book` VALUES ('7', '遥感物理基础', '石文轩', '[4]晏磊,陈伟等. 偏振遥感物理[M]. 科学出版社, 2014.', null, null, '.133.168.206:8888/');
INSERT INTO `book` VALUES ('8', '遥感物理基础', '石文轩', '[5]赵永强,潘泉等. 成像偏振光谱遥感及应用[M]. 国防工业出版社,2011.', null, null, '.133.168.206:8888/');
INSERT INTO `book` VALUES ('9', '遥感物理基础', '石文轩', '[6] 赵凯华. 新概念物理[M]. 高等教育出版社, 2004.', null, null, '.133.168.206:8888/');
INSERT INTO `book` VALUES ('10', '遥感物理基础', '石文轩', '[7] 孙星和. 宇航遥感物理基础[M]. 地震出版社,1990.', null, null, '.133.168.206:8888/');
INSERT INTO `book` VALUES ('11', '遥感物理基础', '石文轩', '[8] 徐希孺. 遥感物理[M].北京大学出版社, 2005.', null, null, '.133.168.206:8888/');
INSERT INTO `book` VALUES ('12', '数字图像处理', '贾永红', '[1]贾永红. 数字图像处理(第三版). 武汉大学出版社, 2015.', null, null, null);
INSERT INTO `book` VALUES ('13', '数字图像处理', '贾永红', '[2] Kenneth. R.Castleman. 数字图像处理. 电子工业出版社, 2002.', null, null, null);
INSERT INTO `book` VALUES ('14', '数字图像处理', '贾永红', '[3]贾永红,崔卫红,余卉. 数字图像处理实习教程(第三版). 武汉大学出版社, 2016.', null, null, null);
INSERT INTO `book` VALUES ('15', '数字图像处理', '贾永红', '[4]杨枝灵,王开等. Visual C++数字图像获取、处理及其实践应用. 人民邮电出版社, 2003.', null, null, null);
INSERT INTO `book` VALUES ('16', '空间数据误差处理', '张永军', '[1]武汉大学测绘学院测量平差学科组. 误差理论与测量平差基础. 武汉大学出版社, 2018.', null, null, null);
INSERT INTO `book` VALUES ('17', '空间数据误差处理', '张永军', '[2]魏克让,江聪世. 空间数据的误差处理. 科学出版社, 2003.', null, null, null);
INSERT INTO `book` VALUES ('18', '遥感原理与方法', '方圣辉', '[1]孙家柄. 遥感原理与应用(第三版). 武汉大学出版社, 2011.', null, null, null);
INSERT INTO `book` VALUES ('19', '遥感原理与方法', '方圣辉', '[2] Thomas M. Lillesand ,Ralph W. Kiefer著, 彭望绿等译. 遥感与影像解译(第四版). 电子工业出版社, 2003.', null, null, null);
INSERT INTO `book` VALUES ('20', '遥感原理与方法', '方圣辉', '[3]赵英时. 遥感应用分析原理与方法(第一版). 科学出版社, 2003.', null, null, null);
INSERT INTO `book` VALUES ('21', '遥感原理与方法', '方圣辉', '[4]周成虎等. 遥感影像地学理解与分析. 科学出版社, 2003.', null, null, null);
INSERT INTO `book` VALUES ('22', '地理信息系统基础', '秦昆', '[1] 龚健雅,秦昆,唐雪华,乐鹏,程朋根. 地理信息系统基础(第二版). 科学出版社, 2019.', null, null, null);
INSERT INTO `book` VALUES ('23', '地理信息系统基础', '秦昆', '[2] Paul A. Longley, Michael F.Goodchild, David J.Maguire, David W.Rhind著,唐中实,黄俊峰,尹平,朱丽云,王越国,王淑伟,李小乙等译. 地理信息系统??原理与技术(上卷、下卷). 电子工业出版社, 2004.', null, null, null);
INSERT INTO `book` VALUES ('24', '计算机视觉与模式识别', '季顺平', '[1]Richard Szeliski. Computer Vision: Algorithms and Applications. Springer, 2010.', null, null, null);
INSERT INTO `book` VALUES ('25', '计算机视觉与模式识别', '季顺平', '[2]Theodoridis. Pattern Recognition (fourth edition). Elsevier Academic Press, 2016.', null, null, null);
INSERT INTO `book` VALUES ('26', '计算机视觉与模式识别', '季顺平', '[3]季顺平. 智能摄影测量学导论. 科学出版社, 2018. ', null, null, null);
INSERT INTO `book` VALUES ('27', '计算机视觉与模式识别', '季顺平', '[4]Richard Hartley and Andrew Zisserman. Multiple View Geometry in Computer Vision. Cambridge University Press, 2003.', null, null, null);
INSERT INTO `book` VALUES ('28', '计算机视觉与模式识别', '季顺平', '[5]David Forsyth and Jean Ponce. Computer Vision: A Modern Approach. Pearson, 2012.', null, null, null);
INSERT INTO `book` VALUES ('29', '计算机视觉与模式识别', '季顺平', '[6]Andrew Webb and Keith Copsey. Statistical Pattern Recognition (Third edition). WILEY Publication, 2016.', null, null, null);
INSERT INTO `book` VALUES ('30', '计算机视觉与模式识别', '季顺平', '[7]Christopher Bishop. Pattern Recognition and Machine Learning. Springer, 2010.', null, null, null);
INSERT INTO `book` VALUES ('31', '计算机视觉与模式识别', '季顺平', '[8]Ian Goodfellow, Yoshua Bengio and Aaron Courville. Deep learning. MIT Press, 2016.', null, null, null);
INSERT INTO `book` VALUES ('32', 'GIS工程设计与开发', '孟庆祥', '[1]毕硕本等. 地理信息系统软件工程的原理与方法. 科学出版社, 2013.', null, null, null);
INSERT INTO `book` VALUES ('33', 'GIS工程设计与开发', '孟庆祥', '[2]李满春. GIS设计与实现. 科学出版社, 2014.', null, null, null);
INSERT INTO `book` VALUES ('34', 'GIS工程设计与开发', '孟庆祥', '[3]邬伦等. 地理信息系统：原理、方法和应用. 科学出版社, 2017.', null, null, null);
INSERT INTO `book` VALUES ('35', '计算社会学与社会地理计算', '秦昆', '自编讲义', null, null, null);
INSERT INTO `book` VALUES ('36', '微机接口', '毛庆洲', '[1]吴宁,乔亚男主编. 微型计算机原理与接口技术(第4版). 清华大学出版社, 2016.', null, null, null);
INSERT INTO `book` VALUES ('37', '微机接口', '毛庆洲', '[2]Charles Elachi, Jakob van zyl. John Wiley & Sons, Inc. Introduction to the physics and techniques of remote sensing. Second edition. Hoboken, New Jersey, 2006.', null, null, null);
INSERT INTO `book` VALUES ('38', '微机接口', '毛庆洲', '[3]W.G.Rees. Physical Principles of Remote Sensing, Second Edition. Cambridge University Press, 2001.', null, null, null);
INSERT INTO `book` VALUES ('39', '微机接口', '毛庆洲', '[4]周荷琴,冯焕清. 微型计算机原理与接口技术(第5版). 中国科学技术大学出版社, 2013.', null, null, null);
INSERT INTO `book` VALUES ('40', '微机接口', '毛庆洲', '[5]于天河,蒋少禹. 微机原理与接口技术习题解答及实验指导. 中国铁道出版社, 2011.', null, null, null);
INSERT INTO `book` VALUES ('41', '微机接口', '毛庆洲', '[6]刘云玲,刘彤,袁刚编著. 微机原理与接口技术实验指导. 清华大学出版社, 2014.', null, null, null);
INSERT INTO `book` VALUES ('42', '微机接口', '毛庆洲', '[7]戴梅萼,史嘉权编著. 微型计算机技术及应用(第4版). 清华大学出版社, 2015.', null, null, null);
INSERT INTO `book` VALUES ('43', '微机接口', '毛庆洲', '[8]马兹迪等著. x86 PC汇编语言、设计与接口(第5版). 电子工业出版社, 2009.', null, null, null);
INSERT INTO `book` VALUES ('44', '空间信息移动编程', '沙宗尧', '[1]邓淑明,胡思仁著,曾杉译. 地理信息网络服务与应用. 科学出版社, 2004. ', null, null, null);
INSERT INTO `book` VALUES ('45', '空间信息移动编程', '沙宗尧', '[2]庄东,刘晓华著. JBuilderX无线应用开发. 电子工业出版社, 2004. ', null, null, null);
INSERT INTO `book` VALUES ('46', '前沿知识讲座', '沙宗尧', '[1]林珲,施迅. 地理信息科学前沿. 高等教育出版社, 2017. ', null, null, null);
INSERT INTO `book` VALUES ('47', '前沿知识讲座', '沙宗尧', '[2]赵英时等著. 遥感应用分析原理与方法. 科学出版社, 2003. ', null, null, null);
INSERT INTO `book` VALUES ('48', '时空数据库课程设计', '沙宗尧', '[1]陈永刚. 开源GIS与空间数据库实战教程. 清华大学出版社, 2016. ', null, null, null);
INSERT INTO `book` VALUES ('49', '时空数据库课程设计', '沙宗尧', '[2]吴信才. 空间数据库. 科学出版社, 2009. ', null, null, null);
INSERT INTO `book` VALUES ('50', '时空数据库课程设计', '沙宗尧', '[3]郝忠孝. 数据库应用理论系列图书:空间数据库理论基础, 科学出版社, 2013.', null, null, null);
INSERT INTO `book` VALUES ('51', 'Java网络程序设计', '孟庆祥', '[1]朱福喜. Java语言程序设计(第二版). 清华大学出版社, 2009. ', null, null, null);
INSERT INTO `book` VALUES ('52', 'Java网络程序设计', '孟庆祥', '[2]耿祥义,张跃平. Java2 实用教程. 清华大学出版社, 2006. ', null, null, null);
INSERT INTO `book` VALUES ('53', 'Java网络程序设计', '孟庆祥', '[3]Herbert Schildt著,张玉清,吴浦峰,尚勇等译. Java2参考大全(第四版). 清华大学出版社. ', null, null, null);
INSERT INTO `book` VALUES ('54', 'Java网络程序设计', '孟庆祥', '[4]C.Thomas wu. 面向对象程序设计导论. 电子工业出版社. ', null, null, null);
INSERT INTO `book` VALUES ('55', 'Java网络程序设计', '孟庆祥', '[5]印?F. Java语言与面向对象程序设计. 清华大学出版社, 2017. ', null, null, null);
INSERT INTO `book` VALUES ('56', '计算机网络与应用', '于子凡', '[1]谢希仁. 计算机网络(第5版). 电子工业出版社, 2008. ', null, null, null);
INSERT INTO `book` VALUES ('57', '计算机网络与应用', '于子凡', '[2]蔡开裕. 计算机网络. 机械工业出版社, 2000. ', null, null, null);
INSERT INTO `book` VALUES ('58', '电子线路基础课程实习', '石文轩', '[1]佘新平. 数字电路设计,仿真,测试. 华中理工大学出版社, 2010. ', null, null, null);
INSERT INTO `book` VALUES ('59', '电子线路基础课程实习', '石文轩', '[2]佘新平. 数字电子技术(第二版). 华中科技大学出版社, 2016. ', null, null, null);
INSERT INTO `book` VALUES ('60', '电子线路基础课程实习', '石文轩', '[3]康华光. 电子技术基础:数字部分(第5版). 高等教育出版社, 2006. ', null, null, null);
INSERT INTO `book` VALUES ('61', '遥感图像解译课程实习', '卞萌', '[1]关泽群,刘继琳. 遥感图像解译. 武汉大学出版社, 2006. ', null, null, null);
INSERT INTO `book` VALUES ('62', '遥感图像解译课程实习', '卞萌', '[2]《遥感图像解译课程综合实习》实习指导书（自编）', null, null, null);
INSERT INTO `book` VALUES ('63', '遥感图像解译课程实习', '卞萌', '[3] Thomas M. Lillesand ,Ralph W. Kiefer著, 彭望绿等译. 遥感与影像解译(第四版). 电子工业出版社, 2003.', null, null, null);
INSERT INTO `book` VALUES ('64', '遥感图像解译课程实习', '卞萌', '[3]孙家?m. 遥感原理与应用(第三版). 武汉：武汉大学出版社, 2011.', null, null, null);
INSERT INTO `book` VALUES ('65', '遥感图像解译课程实习', '卞萌', '[4]赵英时. 遥感应用分析原理与方法(第一版). 北京：科学出版社, 2003.', null, null, null);
INSERT INTO `book` VALUES ('66', '遥感图像解译课程实习', '卞萌', '[5]周成虎等. 遥感影像地学理解与分析. 北京：科学出版社, 2003.', null, null, null);
INSERT INTO `book` VALUES ('67', '遥感图像解译课程实习', '卞萌', '[6]航空摄影像片判读(第一版),测绘出版社,A. H. 日维钦, 1988.', null, null, null);
INSERT INTO `book` VALUES ('68', '遥感图像解译课程实习', '卞萌', '[7]濮静娟. 遥感图像目视解译原理与方法(第一版). 中国科学技术出版社, 1992.', null, null, null);
INSERT INTO `book` VALUES ('69', '地理数据分析与建模课程实习', '卞萌', '[1]《地理国情数据分析与建模实习指导书》（自编）', null, null, null);
INSERT INTO `book` VALUES ('70', '地理数据分析与建模课程实习', '卞萌', '[2]徐建华. 计量地理学. 高等教育出版社, 2009. ', null, null, null);
INSERT INTO `book` VALUES ('71', '地理数据分析与建模课程实习', '卞萌', '[3]史文中,陈江平,张鹏林. 地理国情监测理论与技术. 科学出版社, 2013. ', null, null, null);
INSERT INTO `book` VALUES ('72', '地理数据分析与建模课程实习', '卞萌', '[4] Moore, David S. Introduction to the Practice of Statistics. W. H. Freeman, 2010.', null, null, null);
INSERT INTO `book` VALUES ('73', '激光与红外遥感', '徐景中', '[1]Jie Shan, Charles K. Toth. Topographic Laser Ranging and Scanning Principles and Processing [M]. CRC Press, 2008.', null, null, null);
INSERT INTO `book` VALUES ('74', '激光与红外遥感', '徐景中', '[2]李树楷,薛永祺著. 高效三维遥感集成技术系统[M]. 科学出版社, 2000.', null, null, null);
INSERT INTO `book` VALUES ('75', '激光与红外遥感', '徐景中', '[3]舒宁. 激光成像[M]. 武汉大学出版社, 2005.', null, null, null);
INSERT INTO `book` VALUES ('76', '激光与红外遥感', '徐景中', '[4]赖旭东. 机载激光雷达基础原理与应用[M]. 电子工业出版社, 2010.', null, null, null);
INSERT INTO `book` VALUES ('77', '激光与红外遥感', '徐景中', '[5]王春晖,陈德应. 激光雷达系统设计[M]. 科学出版社, 2014.', null, null, null);
INSERT INTO `book` VALUES ('78', '激光与红外遥感', '徐景中', '[6]舒嵘,等. 激光雷达成像原理与运动误差补偿方法[M]. 科学出版社, 2014.', null, null, null);
INSERT INTO `book` VALUES ('79', '激光与红外遥感', '徐景中', '[7]田国良,等. 热红外遥感[M]. 电子工业出版社, 2014.', null, null, null);
INSERT INTO `book` VALUES ('80', '空间数据分析', '秦昆', '[1]秦昆等. GIS空间分析理论与方法(第二版). 武汉: 武汉大学出版社, 2010.', null, null, '.133.170.5:8888/');
INSERT INTO `book` VALUES ('81', '空间数据分析', '秦昆', '[2]Christopher D.Lloyd. Local Models for Spatial Analysis (Second Edition). CRC Press, 2010. ', null, null, null);
INSERT INTO `book` VALUES ('82', '空间数据分析', '秦昆', '[3]Robert Haining. Spatial Data Analysis: Theory and Practice. Cambridge University Press. Cambridge, 2003.', null, null, null);
INSERT INTO `book` VALUES ('83', '微波遥感课程实习', '潘斌', '[1] 郭华东,邵芸,王长林. 雷达对地观测理论与应用. 科学出版社, 2000.', null, null, null);
INSERT INTO `book` VALUES ('84', '微波遥感课程实习', '潘斌', '[2] Woodhouse I H. Introduction to Microwave Remote Sensing. CRC press, 2005.', null, null, null);
INSERT INTO `book` VALUES ('85', '微波遥感课程实习', '潘斌', '[3] Woodhouse I H. Thirteen short chapters of Remote Sensing. 2012.', null, null, null);
INSERT INTO `book` VALUES ('86', '微波遥感', '潘斌', '[1] 郭华东,邵芸,王长林. 雷达对地观测理论与应用. 科学出版社, 2000.', null, null, null);
INSERT INTO `book` VALUES ('87', '微波遥感', '潘斌', '[2] Woodhouse I H. Introduction to Microwave Remote Sensing. CRC press, 2005.', null, null, null);
INSERT INTO `book` VALUES ('88', '微波遥感', '潘斌', '[3] Woodhouse I H. Thirteen short chapters of Remote Sensing. 2012.', null, null, null);
INSERT INTO `book` VALUES ('89', '摄影测量学', '刘亚文', '[1]张剑清,潘励,王树根编. 摄影测量学(第二版). 武汉大学出版社, 2009.', null, null, null);
INSERT INTO `book` VALUES ('90', '摄影测量学', '刘亚文', '[2]王之卓编著. 摄影测量原理(第一版). 测绘出版社, 2007.', null, null, null);
INSERT INTO `book` VALUES ('91', '摄影测量学', '刘亚文', '[3]王之卓编著. 摄影测量原理续编(第二版). 测绘出版社, 2007.', null, null, null);
INSERT INTO `book` VALUES ('92', '摄影测量学', '刘亚文', '[4]李德仁,郑肇葆编著. 解析摄影测量学. 测绘出版社, 1992.', null, null, null);
INSERT INTO `book` VALUES ('93', '摄影测量学', '刘亚文', '[5]张祖勋,张剑清编著. 数字摄影测量学(第二版). 武汉大学出版社, 2009.', null, null, null);
INSERT INTO `book` VALUES ('94', '摄影测量学课程实习', '刘亚文', '[1]段延松. 数字摄影测量4D生产综合实习教程[M]. 武汉：武汉大学出版社, 2014.', null, null, null);
INSERT INTO `book` VALUES ('95', '摄影测量学课程实习', '刘亚文', '[2]数字摄影测量4D生产综合实习教程、virtuoZo教育版操作手册电子版.', null, null, null);
INSERT INTO `book` VALUES ('96', '摄影测量学课程实习', '刘亚文', '[3]张祖勋,张剑清. 数字摄影测量学(第二版)[M]. 武汉：武汉大学出版社, 2012.', null, null, null);
INSERT INTO `book` VALUES ('97', '摄影测量学课程实习', '刘亚文', '[4]张剑清,潘励,王树根编. 摄影测量学(第二版). 武汉大学出版社, 2009.', null, null, null);
INSERT INTO `book` VALUES ('98', '空间数据分析课程实习', '康朝贵', '[1]秦昆等. GIS空间分析理论与方法(第二版). 武汉: 武汉大学出版社, 2010.', null, null, null);
INSERT INTO `book` VALUES ('99', '空间数据分析课程实习', '康朝贵', '[2]Christopher D.Lloyd. Local Models for Spatial Analysis (Second Edition). CRC Press, 2010. ', null, null, null);
INSERT INTO `book` VALUES ('100', '空间数据分析课程实习', '康朝贵', '[3]Robert Haining. Spatial Data Analysis: Theory and Practice. Cambridge University Press. Cambridge, 2003.', null, null, null);
INSERT INTO `book` VALUES ('101', '空间信息感知与应用', '张目', '自编教材,待出版', null, null, null);
INSERT INTO `book` VALUES ('102', '空间信息感知与应用课程实习', '孟小亮', '[1]孟小亮. 空间信息与传感器网络[M]. 测绘出版社.', null, null, null);
INSERT INTO `book` VALUES ('103', '空间信息感知与应用课程实习', '孟小亮', '[2]边馥苓. 用数字的眼光看世界[M]. 武汉大学出版社. ', null, null, null);
INSERT INTO `book` VALUES ('104', '空间信息感知与应用课程实习', '孟小亮', '[3]边馥苓. 空间信息导论[M]. 测绘出版社.', null, null, null);
INSERT INTO `book` VALUES ('105', '空间信息感知与应用课程实习', '孟小亮', '[4]边馥苓. 数字工程的原理与方法[M]. 测绘出版社.', null, null, null);
INSERT INTO `book` VALUES ('106', '空间信息感知与应用课程实习', '孟小亮', '[5]边馥苓,崔晓晖. 时空大数据的技术与方法[M].测绘出版社. ', null, null, null);
INSERT INTO `book` VALUES ('107', '空间信息感知与应用课程实习', '孟小亮', '[6]孟小亮,边馥苓,崔晓晖. 地信产业卓越工程师培养模式探索[J],测绘科学,2015(8):161-166. ', null, null, null);
INSERT INTO `book` VALUES ('108', '空间信息感知与应用课程实习', '孟小亮', '[7]孟小亮,徐超,边馥苓等. 一种利用空间信息与数字技术专业知识的“互联网＋”创新创业方法[J],测绘通报,2017(12):138-141. ', null, null, null);
INSERT INTO `book` VALUES ('109', '计算机图形学', '付仲良', '[1]孙家广等. 计算机图形学(第三版). 清华大学出版社, 1998. ', null, null, null);
INSERT INTO `book` VALUES ('110', '计算机图形学', '付仲良', '[2]倪明田等. 计算机图形学. 北京大学出版社, 1998. ', null, null, null);
INSERT INTO `book` VALUES ('111', '计算机图形学', '付仲良', '[3]唐泽圣等. 计算机图形学基础. 清华大学出版社, 1998. ', null, null, null);
INSERT INTO `book` VALUES ('112', '计算机图形学', '付仲良', '[4]Donald Hearn, M.Pauline Baker. Computer Graphics. 电子工业出版社, 1997. ', null, null, null);
INSERT INTO `book` VALUES ('113', '计算机图形学课程设计', '付仲良', '[1]于子凡. 计算机图形学实习教程. 武汉大学出版社, 2018. ', null, null, null);
INSERT INTO `book` VALUES ('114', '计算机图形学课程设计', '付仲良', '[2]孙家广等. 计算机图形学(第三版). 清华大学出版社, 1998.', null, null, null);
INSERT INTO `book` VALUES ('115', '科技写作(双语)', '毛飞跃', '[1]任胜利. 英语科技论文撰写与投稿[M]. 科学出版社, 2004.', null, null, null);
INSERT INTO `book` VALUES ('116', '科技写作(双语)', '毛飞跃', '[2]利伯恩[法]著. 任胜利等译.科技英语写作进阶[M]. 科学出版社, 2009', null, null, null);
INSERT INTO `book` VALUES ('117', '科技写作(双语)', '毛飞跃', '[3]毛飞跃,田礼乔,马盈盈. 创新、写新与秀新??对遥感科技论文写作及其教学的总结与思考. 华中师范大学学报(自然科学版), 2016. ', null, null, null);
INSERT INTO `book` VALUES ('118', '地理信息系统基础课程实习', '艾明耀', '[1]《地理信息系统基础课程实习》指导书（自编）', null, null, null);
INSERT INTO `book` VALUES ('119', '地理信息系统基础课程实习', '艾明耀', '[2]牟乃夏. ArcGIS 10 地理信息系统教程?从初学到精通. 测绘出版社, 2012. ', null, null, null);
INSERT INTO `book` VALUES ('120', '地理信息系统基础课程实习', '艾明耀', '[3]汤国安,杨昕. ArcGIS地理信息系统空间分析实验教程(第二版). 科学出版社, 2015. ', null, null, null);
INSERT INTO `book` VALUES ('121', '地理信息系统基础课程实习', '艾明耀', '[4]张康聪著,陈健飞,连莲译. 地理信息系统导论(第7版). 电子工业出版社, 2014. ', null, null, null);
INSERT INTO `book` VALUES ('122', '地理信息系统基础课程实习', '艾明耀', '[5]薛在军. ArcGIS地理信息系统大全. 清华大学出版社, 2013. ', null, null, null);
INSERT INTO `book` VALUES ('123', '数字测图与GNSS测量综合实习', '陈智勇', '[1]《数字测图与GNSS测量综合实习》指导书', null, null, null);
INSERT INTO `book` VALUES ('124', '数字测图与GNSS测量综合实习', '陈智勇', '[2]潘正风. 数字地形测量学. 武汉大学出版社, 2015. ', null, null, null);
INSERT INTO `book` VALUES ('125', '数字测图与GNSS测量综合实习', '陈智勇', '[3]国家基本比例尺地图图式第1部分1:500, 1:1000, 1:2000 地形图图式. 中国标准出版社, 2007. ', null, null, null);
INSERT INTO `book` VALUES ('126', '数字测图与GNSS测量综合实习', '陈智勇', '[4]全球定位系统(GPS)测量规范. 国标准出版社, 2009. ', null, null, null);
INSERT INTO `book` VALUES ('127', '数字测图与GNSS测量综合实习', '陈智勇', '[5]城市测量规范. 中国建筑工业出版社, 2011. ', null, null, null);
INSERT INTO `book` VALUES ('128', '地理信息网络服务', '桂志鹏', '[1]乐鹏. 网络地理信息系统和服务[M]. 武汉大学出版社, 2011.', null, null, null);
INSERT INTO `book` VALUES ('129', '地理信息网络服务', '桂志鹏', '[2]崔铁军. 地理信息服务导论[M]. 科学出版社, 2010.', null, null, null);
INSERT INTO `book` VALUES ('130', '地理信息网络服务', '桂志鹏', '[3]吴华意,章汉武,桂志鹏,沈盛? . 地理信息服务质量的理论与方法[M]. 武汉大学出版社, 2011.', null, null, null);
INSERT INTO `book` VALUES ('131', '地理信息网络服务', '桂志鹏', '[4]龚健雅. 当代地理信息技术[M]. 科学出版社, 2006。', null, null, null);
INSERT INTO `book` VALUES ('132', '虚拟现实技术', '林志勇', '[1]张茂军. 虚拟现实系统. 科学出版社, 2002. ', null, null, null);
INSERT INTO `book` VALUES ('133', '虚拟现实技术', '林志勇', '[2]黄心渊. 虚拟现实技术与应用. 科学出版社, 1999. ', null, null, null);
INSERT INTO `book` VALUES ('134', '虚拟现实技术', '林志勇', '[3]石教英. 虚拟现实基础及实用算法. 科学出版社, 2002. ', null, null, null);
INSERT INTO `book` VALUES ('135', '虚拟现实技术', '林志勇', '[4]William R.Sherman,Alan B.Craig. 虚拟现实系统--接口、应用与设计. 电子工业出版社, 2004. ', null, null, null);
INSERT INTO `book` VALUES ('136', '虚拟现实技术', '林志勇', '[5]龚建华,林珲. 虚拟现实技术与应用. 科学出版社, 1999. ', null, null, null);
INSERT INTO `book` VALUES ('137', '虚拟现实技术', '林志勇', '[6]刘晓艳,林珲,张宏. 虚拟城市建设原理与方法. 科学出版社, 2003. ', null, null, null);
INSERT INTO `book` VALUES ('138', '地理调查方法与编码', '胡庆武', '[1]胡庆武,王少华,艾明耀. 地理调查与编码[M]. 武汉大学出版社, 2015.', null, null, null);
INSERT INTO `book` VALUES ('139', '地理调查方法与编码', '胡庆武', '[2]过宝兴. 地理调查研究方法(第2版) [M]. 高等教育出版社, 2001. ', null, null, null);
INSERT INTO `book` VALUES ('140', '地理调查方法与编码', '胡庆武', '[3]张根寿. 庐山地理调查[M]. 武汉大学出版社, 2004. ', null, null, null);
INSERT INTO `book` VALUES ('141', '地理调查方法与编码课程实习', '胡庆武', '[1]地理调查与编码实习指导书（自编）', null, null, null);
INSERT INTO `book` VALUES ('142', '地理调查方法与编码课程实习', '胡庆武', '[2]胡庆武,王少华,艾明耀. 地理调查与编码[M]. 武汉大学出版社, 2015. ', null, null, null);
INSERT INTO `book` VALUES ('143', '地理调查方法与编码课程实习', '胡庆武', '[3]《GDPJ 02?2013 地理国情普查基本统计技术规定》', null, null, null);
INSERT INTO `book` VALUES ('144', '地理调查方法与编码课程实习', '胡庆武', '[4]《GDPJ 03-2013地理国情普查数据规定与采集要求》', null, null, null);
INSERT INTO `book` VALUES ('145', '地理调查方法与编码课程实习', '胡庆武', '[5]《GDPJ 01-2013地理国情普查内容与指标》', null, null, null);
INSERT INTO `book` VALUES ('146', 'GIS工程设计与开发课程实习', '孟庆祥', '实习指导书（自编）', null, null, null);
INSERT INTO `book` VALUES ('147', '近景摄影测量', '李欣', '[1]冯文灏. 近景摄影测量. 武汉大学出版社, 2003. ', null, null, null);
INSERT INTO `book` VALUES ('148', '近景摄影测量', '李欣', '[2]李德仁,郑肇葆. 解析摄影测量学. 测绘出版社, 1992.', null, null, null);
INSERT INTO `book` VALUES ('149', '近景摄影测量', '李欣', '[3]张剑清,潘励,王树根. 摄影测量学(第二版). 武汉大学出版社, 2017.', null, null, null);
INSERT INTO `book` VALUES ('150', '近景摄影测量', '李欣', '[4]王之卓. 摄影测量原理. 测绘出版社, 1992.', null, null, null);
INSERT INTO `book` VALUES ('151', '近景摄影测量课程设计', '李欣', '[1]冯文灏. 近景摄影测量. 武汉大学出版社, 2003. ', null, null, null);
INSERT INTO `book` VALUES ('152', '近景摄影测量课程设计', '李欣', '[2]武汉大学测绘学院测量平差学科组. 误差理论与测量平差基础. 武汉大学出版社, 2014.', null, null, null);
INSERT INTO `book` VALUES ('153', '近景摄影测量课程设计', '李欣', '[3]张剑清,潘励,王树根. 摄影测量学(第二版). 武汉大学出版社, 2017.', null, null, null);
INSERT INTO `book` VALUES ('154', '数据库原理及应用', '杜娟', '[1]王珊,萨师煊. 数据库系统概论(第5版). 北京:高等教育出版社, 2014.', null, null, null);
INSERT INTO `book` VALUES ('155', '数据库原理及应用', '杜娟', '[2]李俊山. 数据库原理与应用[M]. 北京:清华大学出版社, 2017.', null, null, null);
INSERT INTO `book` VALUES ('156', '数据库原理及应用', '杜娟', '[3]高春艳. SQL Server应用与开发范例宝典 [M]. 北京:人民邮电出版社, 2015.', null, null, null);
INSERT INTO `book` VALUES ('157', '数据库原理及应用', '杜娟', '[4]岳丽华等. 数据库系统概论[M]. 北京:科学出版社, 2000.', null, null, null);
INSERT INTO `book` VALUES ('158', '数据库原理及应用课程实习', '季铮', '[1]《数据库原理与应用课程设计》实习指导书（自编）', null, null, null);
INSERT INTO `book` VALUES ('159', '数据库原理及应用课程实习', '季铮', '[2]王珊,萨师煊. 数据库系统概论(第5版). 北京:高等教育出版社, 2014.', null, null, null);
INSERT INTO `book` VALUES ('160', '数据库原理及应用课程实习', '季铮', '[3]叶霞,罗蓉,李俊山. 数据库原理及应用(SQL Server)实验教程. 清华大学出版社, 2014.', null, null, null);
INSERT INTO `book` VALUES ('161', '时空数据库', '张鹏林', '[1]吴信才. 空间数据库[M]. 科学出版社, 2009.', null, null, null);
INSERT INTO `book` VALUES ('162', '时空数据库', '张鹏林', '[2] Philippe Rigaux. SPATIAL DATABASES with application to GIS. Morgan Kaufmann Publishers, 2001.', null, null, null);
INSERT INTO `book` VALUES ('163', '时空数据库', '张鹏林', '自编教材', null, null, null);
INSERT INTO `book` VALUES ('164', '空间数据库', '余长慧', '[1]吴信才. 空间数据库[M]. 科学出版社, 2009.', null, null, null);
INSERT INTO `book` VALUES ('165', '空间数据库', '余长慧', '[2]Albert K..W. Yeung、G..Brent Hall. Spatial Database System. Springer, 2007. ', null, null, null);
INSERT INTO `book` VALUES ('166', '空间数据库', '余长慧', '[3]张新长,马林兵,张青年. 地理信息系统数据库. 科学出版社, 2005. ', null, null, null);
INSERT INTO `book` VALUES ('167', '空间数据库', '余长慧', '[4] Yannis Manolopoulos, Apostolos N. Papadopoulos, Michael Gr. Vassilakopoulos. Spatial Databases: Technologies, Techniques and Trends. IDEA GROUP PUBLISHING, 2005. ', null, null, null);
INSERT INTO `book` VALUES ('168', '空间数据库', '余长慧', '[5]郭际元,周顺平,刘修国. 空间数据库. 科学出版社, 2004. ', null, null, null);
INSERT INTO `book` VALUES ('169', '空间数据库', '余长慧', '[6] Philippe Rigaux, Michel Scholl, Agnes Voisard. Spatial Databases: with application to GIS. Morgan Kaufmann Publishers, 2002. ', null, null, null);
INSERT INTO `book` VALUES ('170', '空间数据库课程设计', '余长慧', '[1]吴信才. 空间数据库[M]. 科学出版社, 2009.', null, null, null);
INSERT INTO `book` VALUES ('171', '空间数据库课程设计', '余长慧', '[2]Albert K..W. Yeung、G..Brent Hall. Spatial Database System. Springer, 2007. ', null, null, null);
INSERT INTO `book` VALUES ('172', '空间数据库课程设计', '余长慧', '[3]张新长,马林兵,张青年. 地理信息系统数据库. 科学出版社, 2005. ', null, null, null);
INSERT INTO `book` VALUES ('173', '空间数据库课程设计', '余长慧', '[4] Yannis Manolopoulos, Apostolos N. Papadopoulos, Michael Gr. Vassilakopoulos. Spatial Databases: Technologies, Techniques and Trends. IDEA GROUP PUBLISHING, 2005. ', null, null, null);
INSERT INTO `book` VALUES ('174', '空间数据库课程设计', '余长慧', '[5]郭际元,周顺平,刘修国. 空间数据库. 科学出版社, 2004. ', null, null, null);
INSERT INTO `book` VALUES ('175', '空间数据库课程设计', '余长慧', '[6] Philippe Rigaux, Michel Scholl, Agnes Voisard. Spatial Databases: with application to GIS. Morgan Kaufmann Publishers, 2002. ', null, null, null);
INSERT INTO `book` VALUES ('176', '时空数据处理与组织', '周松涛', '[1]自编教材,待出版', null, null, null);
INSERT INTO `book` VALUES ('177', '时空数据处理与组织', '周松涛', '[1]Stephen Wise,朱定局译. GIS数据结构与算法基础. 科学出版社, 2017.', null, null, null);
INSERT INTO `book` VALUES ('178', '时空数据处理与组织', '周松涛', '[2]吴信. GIS开发大变革?云计算模式下MapGIS全新开发模式深度解析. 电子工业出版社, 2015.', null, null, null);
INSERT INTO `book` VALUES ('179', '时空数据处理与组织', '周松涛', '[3]Joel Lawhead. Python地理空间分析指南(第2版). 人民邮电出版社, 2017.', null, null, null);
INSERT INTO `book` VALUES ('180', '时空数据处理与组织', '周松涛', '[4]林子雨. 大数据技术原理与应用(第2版). 人民邮电出版社, 2017.', null, null, null);
INSERT INTO `book` VALUES ('181', '时空数据处理与组织课程实习', '李晓雷', '[1] Joel Lawhead. Python地理空间分析指南(第2版). 人民邮电出版社, 2017.', null, null, null);
INSERT INTO `book` VALUES ('182', '时空数据处理与组织课程实习', '李晓雷', '[2]林子雨. 大数据技术原理与应用(第2版). 人民邮电出版社, 2017.', null, null, null);
INSERT INTO `book` VALUES ('183', '时空数据处理与组织课程实习', '李晓雷', '[3]Stephen Wise,朱定局译. GIS数据结构与算法基础. 科学出版社, 2017.', null, null, null);
INSERT INTO `book` VALUES ('184', '时空数据处理与组织课程实习', '李晓雷', '[4]汤国安,杨昕. ArcGIS地理信息系统空间分析实验教程(第二版). 科学出版社, 2015.', null, null, null);
INSERT INTO `book` VALUES ('185', '时空数据分析与挖掘', '田扬戈', '[1] Harvey J. Miller,Jiawei Han. Geographic Data Mining and Knowledge Discovery (2.ed). CRC Press, 2009. ', null, null, null);
INSERT INTO `book` VALUES ('186', '时空数据分析与挖掘', '田扬戈', '[2]韩家炜. 数据挖掘:概念与技术(第3版). 机械工业出版社, 2012. ', null, null, null);
INSERT INTO `book` VALUES ('187', '时空数据分析与挖掘', '田扬戈', '[3] Pang-Ning Tan,Michael Steinbach,Vipin Kumar. 数据挖掘导论(第2版). 人民邮电出版社, 2011. ', null, null, null);
INSERT INTO `book` VALUES ('188', '时空数据分析与挖掘', '田扬戈', '[4] Jonathan D.Cryer,Kung-Sik Chan. 时间序列分析及应用. 清华大学出版社, 2011. ', null, null, null);
INSERT INTO `book` VALUES ('189', '时空数据分析与挖掘', '田扬戈', '[5]刘爱利,王培法,丁园圆. 地统计学概论. 清华大学出版社, 2012. ', null, null, null);
INSERT INTO `book` VALUES ('190', '时空数据分析与挖掘', '田扬戈', '', null, null, null);
INSERT INTO `book` VALUES ('191', '时空数据分析与挖掘课程实习', '杨宗亮', '[1] Joel Lawhead. 地理空间分析指南(第2版). 清人民邮电出版社, 2017. ', null, null, null);
INSERT INTO `book` VALUES ('192', '时空数据分析与挖掘课程实习', '杨宗亮', '[2]林子雨. 大数据技术原理与应用(第2版). 人民邮电出版社, 2017.', null, null, null);
INSERT INTO `book` VALUES ('193', '时空数据分析与挖掘课程实习', '杨宗亮', '[3]汤国安,杨昕. ArcGIS地理信息系统空间分析实验教程(第二版). 科学出版社, 2015.', null, null, null);
INSERT INTO `book` VALUES ('194', '时空数据分析与挖掘课程实习', '杨宗亮', '[4]Stephen Wise,朱定局译. GIS数据结构与算法基础. 科学出版社, 2017.', null, null, null);
INSERT INTO `book` VALUES ('195', '时空数据分析与挖掘课程实习', '杨宗亮', '[5]韩家炜. 数据挖掘:概念与技术(第3版). 机械工业出版社, 2012. ', null, null, null);
INSERT INTO `book` VALUES ('196', '数字图像处理课程设计', '杨代琴', '[1]贾永红. 数字图像处理实习教程(第二版)[M]. 武汉大学出版社, 2012.', null, null, null);
INSERT INTO `book` VALUES ('197', '数字图像处理课程设计', '杨代琴', '[1]贾永红. 数字图像处理(第三版)[M]. 武汉大学出版社, 2015.', null, null, null);
INSERT INTO `book` VALUES ('198', '大气与海洋遥感', '毛飞跃', '[1]李万彪. 大气遥感. 北京大学出版社, 2014.', null, null, null);
INSERT INTO `book` VALUES ('199', '大气与海洋遥感', '毛飞跃', '[2]Seelye Martin,蒋兴伟等译. 海洋遥感导论. 海洋出版社, 2008.', null, null, null);
INSERT INTO `book` VALUES ('200', '大气与海洋遥感', '毛飞跃', '[1]王英俭,胡顺星,周军等. 激光雷达大气参数测量. 科学出版社, 2014.', null, null, null);
INSERT INTO `book` VALUES ('201', '大气与海洋遥感', '毛飞跃', '[2]盛裴宣,毛节泰,李建国等. 大气物理学. 北京大学出版社, 2003.', null, null, null);
INSERT INTO `book` VALUES ('202', '大气与海洋遥感', '毛飞跃', '[3]Liou K N,彩丽,诗健等. 大气辐射导论. 气象出版, 2004.', null, null, null);
INSERT INTO `book` VALUES ('203', '大气与海洋遥感', '毛飞跃', '[4]刘良明等. 卫星海洋遥感导论(第一版). 武汉大学出版社, 2005.', null, null, null);
INSERT INTO `book` VALUES ('204', '解析摄影测量', '袁修孝', '[1]张剑清,潘励,王树根. 摄影测量学(第二版) [M]. 武汉大学出版社, 2009.', null, null, null);
INSERT INTO `book` VALUES ('205', '解析摄影测量', '袁修孝', '[2]李德仁,郑肇葆. 解析摄影测量学[M]. 测绘出版社, 1992.', null, null, null);
INSERT INTO `book` VALUES ('206', '解析摄影测量', '袁修孝', '[3]袁修孝. GPS辅助空中三角测量原理及应用[M]. 测绘出版社, 2001.', null, null, null);
INSERT INTO `book` VALUES ('207', '解析摄影测量课程设计', '王 h', '[1]《解析摄影测量课程设计实习指导书》（自编）', null, null, null);
INSERT INTO `book` VALUES ('208', '解析摄影测量课程设计', '王 h', '[2]张祖勋,张剑清. 数字摄影测量学(第二版)[M]. 武汉：武汉大学出版社, 2012.', null, null, null);
INSERT INTO `book` VALUES ('209', '解析摄影测量课程设计', '王 h', '[3]张剑清,潘励,王树根. 摄影测量学(第二版) [M]. 武汉大学出版社, 2009.', null, null, null);
INSERT INTO `book` VALUES ('210', '数字摄影测量', '潘励', '[1]张剑清,潘励,王树根. 摄影测量学(第二版) [M]. 武汉大学出版社, 2009.', null, null, null);
INSERT INTO `book` VALUES ('211', '数字摄影测量', '潘励', '[2]张祖勋. 数字摄影测量学[M](第2版). 武汉大学出版社, 2012.', null, null, null);
INSERT INTO `book` VALUES ('212', '数字摄影测量', '潘励', '[3]解析摄影测量学[M]. 测绘出版社, 1992.', null, null, null);
INSERT INTO `book` VALUES ('213', '数字摄影测量', '潘励', '[4]王之卓. 摄影测量原理[M]. 武汉大学出版社, 2007.', null, null, null);
INSERT INTO `book` VALUES ('214', '数字摄影测量', '潘励', '[5]李德仁. 误差处理与可靠性理论[M] (第2版). 武汉大学出版社, 2012.', null, null, null);
INSERT INTO `book` VALUES ('215', '数字摄影测量课程设计', '季铮', '[1]《数字摄影测量课程设计》实习指导书(自编)', null, null, null);
INSERT INTO `book` VALUES ('216', '数字摄影测量课程设计', '季铮', '[2]张祖勋,张剑清. 数字摄影测量学(第二版)[M]. 武汉：武汉大学出版社, 2012.', null, null, null);
INSERT INTO `book` VALUES ('217', '卫星摄影测量', '赵双明', '[1]张永生,刘军,巩丹超. 高分辨率遥感卫星应用[M]. 科学出版社, 2014.', null, null, null);
INSERT INTO `book` VALUES ('218', '卫星摄影测量', '赵双明', '[2]张过. 线阵推扫式光学卫星几何高精度处理[M]. 科学出版社, 2016.', null, null, null);
INSERT INTO `book` VALUES ('219', '卫星摄影测量', '赵双明', '[3]李德仁,郑肇葆. 解析摄影测量学[M]. 测绘出版社, 1992.', null, null, null);
INSERT INTO `book` VALUES ('220', '卫星摄影测量', '赵双明', '[4]张祖勋,张剑清. 数字摄影测量学[M]. 测绘出版社, 2006.', null, null, null);
INSERT INTO `book` VALUES ('221', '卫星摄影测量', '赵双明', '[5]张过,秦绪文,潘红播,王兴玲. 高分辨率光学卫星标准产品分级体系[M]. 测绘出版社, 2012.', null, null, null);
INSERT INTO `book` VALUES ('222', '当代摄影测量（双语）', '王树根', '[1]张祖勋,张剑清. 数字摄影测量学(第二版)[M]. 武汉：武汉大学出版社, 2012.', null, null, null);
INSERT INTO `book` VALUES ('223', '当代摄影测量（双语）', '王树根', '[2]盛庆红,肖晖. 卫星遥感与摄影测量. 科学出版社, 2014.', null, null, null);
INSERT INTO `book` VALUES ('224', '当代摄影测量（双语）', '王树根', '[3]M.Kasser,Y.Egels. Digital Photogrammetry. Taylor &Francis, 2002.', null, null, null);
INSERT INTO `book` VALUES ('225', '当代摄影测量（双语）', '王树根', '[4]ASPRS. Digital Photogrammetry-An Addendum to the Manual of Photogrammetry. 1996.', null, null, null);
INSERT INTO `book` VALUES ('226', '当代摄影测量（双语）', '王树根', '[5]M. O. Altan, G. Toz, I. Dowman etl, S. Kulur, D. Z. Seker. Guidelines for authors: preparing manuscripts for ISPRS sponsored meetings, 2001.', null, null, null);
INSERT INTO `book` VALUES ('227', '摄影测量学课程实习', '刘亚文', '[1]张祖勋,张剑清. 数字摄影测量学(第二版)[M]. 武汉：武汉大学出版社, 2012.', null, null, null);
INSERT INTO `book` VALUES ('228', '摄影测量学课程实习', '刘亚文', '[2]张剑清,潘励,王树根. 摄影测量学(第二版) [M]. 武汉大学出版社, 2009.', null, null, null);
INSERT INTO `book` VALUES ('229', '摄影测量综合实习', '段延松', '[1]段延松等. 航空摄影测量内业[M]. 武汉大学出版社, 2018.', null, null, null);
INSERT INTO `book` VALUES ('230', '摄影测量综合实习', '段延松', '[2] 段延松等. 数字摄影测量4D生产综合实习教程[M]. 武汉大学出版社, 2014.', null, null, null);
INSERT INTO `book` VALUES ('231', '摄影测量综合实习', '段延松', '[3]张祖勋,张剑清. 数字摄影测量学(第二版)[M]. 武汉：武汉大学出版社, 2012.', null, null, null);
INSERT INTO `book` VALUES ('232', '摄影测量综合实习', '段延松', '[4]张剑清,潘励,王树根. 摄影测量学(第二版) [M]. 武汉大学出版社, 2009.', null, null, null);
INSERT INTO `book` VALUES ('233', '电子线路基础（上）', '毛庆洲', '[1]康华光. 电子技术基础,模拟部分(第6版)[M]. 高等教育出版社, 2013.', null, null, null);
INSERT INTO `book` VALUES ('234', '电子线路基础（上）', '毛庆洲', '[2]清华大学电子学教研组,华成英,童诗白主. 模拟电子技术基础(第五版) [M]. 高等教育出版社, 2015.', null, null, null);
INSERT INTO `book` VALUES ('235', '电子线路基础（上）', '毛庆洲', '[3]华中科技大学电子技术课程组. 电子技术基础 模拟部分 学习辅导与习题解答:第六版[M]. 高等教育出版社, 2014.', null, null, null);
INSERT INTO `book` VALUES ('236', '电子线路基础（上）', '毛庆洲', '[4]华成英. 模拟电子技术基础 (第五版) 学习辅导与习题解答[M]. 高等教育出版社, 2015. ', null, null, null);
INSERT INTO `book` VALUES ('237', '电子线路基础（下）', '毛庆洲', '[1]康华光. 电子技术基础,模拟部分(第6版)[M]. 高等教育出版社, 2013.', null, null, null);
INSERT INTO `book` VALUES ('238', '电子线路基础（下）', '毛庆洲', '[2]亚伯勒[美]. 数字逻辑 应用与设计(英文版)[M]. 机械工业出版社, 2002.', null, null, null);
INSERT INTO `book` VALUES ('239', '定量遥感', '巫兆聪', '[1]陈晓玲,赵红梅,田礼乔主编. 环境遥感模型与应用. 武汉大学出版社, 2008.', null, null, null);
INSERT INTO `book` VALUES ('240', '定量遥感', '巫兆聪', '[2][美]梁顺林著,范文捷等译. 定量遥感. 科学出版社, 2009.', null, null, null);
INSERT INTO `book` VALUES ('241', '定量遥感', '巫兆聪', '[3]Remote Sensing Handbooks：Remote Sensing of Water Resources, Disasters, and Urban Studies. Remotely Sensed Data Characterization, Classification, and Accuracies. Land Resources Monitoring, Modeling, and Mapping with Remote Sensing. CRC Press, 2015.', null, null, null);
INSERT INTO `book` VALUES ('242', '定量遥感课程设计', '彭漪', '[1][美]梁顺林著,范文捷等译. 定量遥感. 科学出版社, 2009.', null, null, null);
INSERT INTO `book` VALUES ('243', '定量遥感课程设计', '彭漪', '[1]柳钦火. 定量遥感模型应用及不确定性研究. 科学出版社, 2016. ', null, null, null);
INSERT INTO `book` VALUES ('244', '网络GIS', '孟令奎', '[1]孟令奎等. 网络地理信息系统原理与技术(第三版). 科学出版社, 2019.', null, null, null);
INSERT INTO `book` VALUES ('245', '网络GIS', '孟令奎', '[2]马林兵等. WebGIS技术原理与应用开发(第二版). 科学出版社, 2012.', null, null, null);
INSERT INTO `book` VALUES ('246', '网络GIS', '孟令奎', '[3]刘光等. Web GIS原理与应用开发. 清华大学出版社, 2016.', null, null, null);
INSERT INTO `book` VALUES ('247', '网络GIS', '孟令奎', '[4]周林等. 网络GIS开发实践入门. 中国地质大学出版社, 2014.', null, null, null);
INSERT INTO `book` VALUES ('248', '网络GIS', '孟令奎', '[5]李治洪. WebGIS原理与实践. 高等教育出版社, 2011.', null, null, null);
INSERT INTO `book` VALUES ('249', '网络GIS课程设计', '黄长青', '[1] ARCGIS Server Web ADF开发》实习指导书（自编）', null, null, null);
INSERT INTO `book` VALUES ('250', '网络GIS课程设计', '黄长青', '[2]《ArcGIS Flex API 开发》实习指导书（自编）', null, null, null);
INSERT INTO `book` VALUES ('251', '网络GIS课程设计', '黄长青', '[3] 何正国. ArcGIS Server开发从入门到精通. 人民邮电出版社, 2010. ', null, null, null);
INSERT INTO `book` VALUES ('252', '网络GIS课程设计', '黄长青', '[4] 刘光. Web GIS开发:ArcGIS Server与.NET. 清华大学出版社, 2009. ', null, null, null);
INSERT INTO `book` VALUES ('253', '地理空间影像的智能处理', '胡翔云', '[1]Sonka et.al., Image Processing, Analysis and Machine Vision (3rd edition). Thomson Corp, 2008.', null, null, null);
INSERT INTO `book` VALUES ('254', '地理空间影像的智能处理', '胡翔云', '[2]高隽. 图像理解理论与方法[M]. 科学出版社, 2009.', null, null, null);
INSERT INTO `book` VALUES ('255', '地理空间影像的智能处理', '胡翔云', '[3]罗四维. 视觉信息认知计算理论[M]. 科学出版社, 2010.', null, null, null);
INSERT INTO `book` VALUES ('256', '地理空间影像的智能处理', '胡翔云', '[4]Ian Goodfellow et.al. Deep Learning. MIT Press, 2016.', null, null, null);
INSERT INTO `book` VALUES ('257', '空间智能计算与服务', '谭喜成', '[1]周志华. 机器学习. 清华大学出版社, 2016. ', null, null, null);
INSERT INTO `book` VALUES ('258', '空间智能计算与服务', '谭喜成', '[1]李霖, 应申. 地理计算原理与方法. 测绘出版社, 2008. ', null, null, null);
INSERT INTO `book` VALUES ('259', '空间智能计算与服务', '谭喜成', '[1]边馥苓. 时空大数据的技术与方法. 测绘出版社, 2016. ', null, null, null);
INSERT INTO `book` VALUES ('260', '空间智能计算与服务', '谭喜成', '[1]乐鹏. 网络地理信息系统和服务. 武汉大学出版社, 2011. ', null, null, null);
INSERT INTO `book` VALUES ('261', '空间智能计算与服务课程实习', '李爽', '[1]秦昆. 智能空间信息处理[M]. 武汉大学出版社, 2009.', null, null, null);
INSERT INTO `book` VALUES ('262', '空间智能计算与服务课程实习', '李爽', '[2]罗伯特?海宁著,李建松,秦昆译. 空间数据分析理论与实践[M]. 武汉大学出版社, 2009.', null, null, null);
INSERT INTO `book` VALUES ('263', '空间智能计算与服务课程实习', '李爽', '[3]秦昆. GIS空间分析理论与方法.第2版[M]. 武汉大学出版社, 2010.', null, null, null);
INSERT INTO `book` VALUES ('264', '空间智能计算与服务课程实习', '李爽', '[4]王艳东, 龚健雅. 空间信息智能服务理论与方法[M]. 科学出版社, 2012.', null, null, null);
INSERT INTO `book` VALUES ('265', '数据结构与算法课程实习', '黄玉春', '[1]严蔚敏等. 数据结构(C语言版). 清华大学出版社. 2011.', null, null, null);
INSERT INTO `book` VALUES ('266', '经济地理', '贾涛', '[1]刘艳芳等编著. 经济地理学??原理、方法与应用[M]. 科学出版社, 2009.', null, null, null);
INSERT INTO `book` VALUES ('267', '经济地理', '贾涛', '[2]李芹芳,任召霞. 经济地理学[M]. 武汉大学出版社, 2010.', null, null, null);
INSERT INTO `book` VALUES ('268', '经济地理', '贾涛', '[3]吴传钧等. 现代经济地理学[M]. 江苏教育出版社, 1997.', null, null, null);
INSERT INTO `book` VALUES ('269', '经济地理', '贾涛', '[4]李小建. 经济地理学[M]. 高等教育出版社, 2006.', null, null, null);
INSERT INTO `book` VALUES ('270', '经济地理', '贾涛', '[5]杨吾杨,梁进社. 高等经济地理学[M]. 北京大学出版社, 2000.', null, null, null);
INSERT INTO `book` VALUES ('271', 'Practice and Applications of Geoinformatics', '贾涛', '[1]Michael Zeiler. Modeling Our World[M]. Environmental Systems Research Institute, Inc.US, 1999.', null, null, null);
INSERT INTO `book` VALUES ('272', 'Practice and Applications of Geoinformatics', '贾涛', '[2]贾涛,李琦,马楚,李雨芊. 武汉市出租车轨迹二氧化碳排放的时空模式分析[J]. 武汉大学学报（信息科学版）, 2018.', null, null, null);
INSERT INTO `book` VALUES ('273', 'Practice and Applications of Geoinformatics', '贾涛', '[3]Tao Jia, Qi Li, Wenzhong Shi. Estimation and analysis of emissions from on-road vehicles in Mainland China for the period 2011?2015 [J]. Atmospheric Environment, 2018.', null, null, null);
INSERT INTO `book` VALUES ('274', 'Practice and Applications of Geoinformatics', '贾涛', '[4]Tao Jia, Bin Jiang. Building and analyzing the US airport network based on en-route location information [J]. Physica A: Statistical Mechanics and its Applications, 2012.', null, null, null);
INSERT INTO `book` VALUES ('275', 'Practice and Applications of Geoinformatics', '贾涛', '[5]Tao Jia, Kun Qin, Jie Shan. An exploratory analysis on the evolution of the US airport network [J]. Physica A: Statistical Mechanics and its Applications, 2014.', null, null, null);
INSERT INTO `book` VALUES ('276', 'Practice and Applications of Geoinformatics', '贾涛', '[6]Tao Jia, Kai Chen, Jiye Wang. Characterizing the Growth Patterns of 45 Major Metropolitans in Mainland China Using DMSP/OLS Data [J]. Remote Sensing, 2017.', null, null, null);
INSERT INTO `book` VALUES ('277', 'Practice and Applications of Geoinformatics', '贾涛', '[7]单杰,贾涛等编著. 众源地理数据分析与应用[M]. 科学出版社, 2017.', null, null, null);
INSERT INTO `book` VALUES ('278', '经济与人文地理', '贾涛', '[1]刘艳芳等编著. 经济地理学??原理、方法与应用[M]. 科学出版社, 2009.', null, null, null);
INSERT INTO `book` VALUES ('279', '经济与人文地理', '贾涛', '[2]李芹芳,任召霞. 经济地理学[M]. 武汉大学出版社, 2010.', null, null, null);
INSERT INTO `book` VALUES ('280', '经济与人文地理', '贾涛', '[3]吴传钧等. 现代经济地理学[M]. 江苏教育出版社, 1997.', null, null, null);
INSERT INTO `book` VALUES ('281', '经济与人文地理', '贾涛', '[4]李小建. 经济地理学[M]. 高等教育出版社, 2006.', null, null, null);
INSERT INTO `book` VALUES ('282', '经济与人文地理', '贾涛', '[5]杨吾杨,梁进社. 高等经济地理学[M]. 北京大学出版社, 2000.', null, null, null);
INSERT INTO `book` VALUES ('283', '经济与人文地理', '贾涛', '[6]陈慧琳等. 人文地理学(第三版) [M]. 科学出版社, 2013.', null, null, null);
INSERT INTO `book` VALUES ('284', '经济与人文地理', '贾涛', '[7]王法辉. 基于GIS的数量方法与应用[M]. 商务印书馆, 2009.', null, null, null);
INSERT INTO `book` VALUES ('285', '高性能地理计算', '乐鹏', '[1]李霖, 应申. 地理计算原理与方法. 测绘出版社, 2008.', null, null, null);
INSERT INTO `book` VALUES ('286', '高性能地理计算', '乐鹏', '[2]迟学斌,王彦?,王珏,刘芳. 并行计算与实现技术. 科学出版社, 2015. ', null, null, null);
INSERT INTO `book` VALUES ('287', '高性能地理计算', '乐鹏', '[3]陈国良. 并行计算??结构?算法?编程. 高等教育出版社, 2011. ', null, null, null);
INSERT INTO `book` VALUES ('288', '地理建模方法', '贾涛', '[1]徐建华. 地理建模方法[M]. 科学出版社, 2010.', null, null, null);
INSERT INTO `book` VALUES ('289', '地理建模方法', '贾涛', '[2]韦玉春等. 地理建模原理与方法[M]. 科学出版社, 2005.', null, null, null);
INSERT INTO `book` VALUES ('290', '地理建模方法', '贾涛', '[3]陈彦光. 地理数学方法：基础和应用[M]. 科学出版社, 2010.', null, null, null);
INSERT INTO `book` VALUES ('291', '地理建模方法', '贾涛', '[4]Michael Zeiler. Modeling Our World[M]. Environmental Systems Research Institute, Inc. US, 1999.', null, null, null);
INSERT INTO `book` VALUES ('292', '地理建模方法', '贾涛', '[5]美国西北大学,Netlogo 用户手册[EB/OL]. https://ccl.northwestern.edu/netlogo/docs/', null, null, null);
INSERT INTO `book` VALUES ('293', '地图学', '黄长青', '[1]马耀峰. 地图学原理. 科学出版社, 2004. ', null, null, null);
INSERT INTO `book` VALUES ('294', '地图学', '黄长青', '[2]袁勘省. 现代地图学教材（第二版）. 科学出版社, 2016. ', null, null, null);
INSERT INTO `book` VALUES ('295', '地图学', '黄长青', '[3]祝国瑞. 地图学. 武汉大学出版社, 2004. ', null, null, null);
INSERT INTO `book` VALUES ('296', '地图学', '黄长青', '[4]何宗宜. 地图学. 武汉大学出版社, 2016. ', null, null, null);
INSERT INTO `book` VALUES ('297', '地图学', '黄长青', '[5]祁向前. 地图学原理. 武汉大学出版社, 2012. ', null, null, null);
INSERT INTO `book` VALUES ('298', '地图学', '黄长青', '[6]王家耀等. 地图学原理与方法（第二版）. 科学出版社, 2014. ', null, null, null);
INSERT INTO `book` VALUES ('299', '地图学', '黄长青', '[7]赵耀龙等. 地图学基础. 科学出版社, 2016. ', null, null, null);
INSERT INTO `book` VALUES ('300', '人工智能与机器学习', '陈震中', '[1] Stuart Russell,Peter Norvig. 人工智能-一种现代方法（第三版）. 人民邮电出版社, 2011. ', null, null, null);
INSERT INTO `book` VALUES ('301', '人工智能与机器学习', '陈震中', '[2]周志华. 机器学习. 清华大学出版社, 2016.', null, null, null);
INSERT INTO `book` VALUES ('302', '人工智能与机器学习', '陈震中', '[3]朱福喜. 人工智能. 清华大学出版社, 2017. ', null, null, null);
INSERT INTO `book` VALUES ('303', '精密机械设计基础', '毛庆洲', '[1]许贤泽,戴书华. 精密机械设计基础（第3版）. 电子工业出版社, 2015. ', null, null, null);
INSERT INTO `book` VALUES ('304', '精密机械设计基础', '毛庆洲', '[2]许贤泽. 精密机械学基础. 华中科技大学出版社, 2009. ', null, null, null);
INSERT INTO `book` VALUES ('305', '精密机械设计基础', '毛庆洲', '[3]庞振基. 精密机械设计. 清华大学出版社, 2009. ', null, null, null);
INSERT INTO `book` VALUES ('306', '精密机械设计基础', '毛庆洲', '[4]许贤泽. 精密机械设计. 电子工业出版社, 2013. ', null, null, null);
INSERT INTO `book` VALUES ('307', '精密机械设计基础', '毛庆洲', '[5]裘祖荣. 精密机械设计基础（第2版）. 机械工业出版社, 2016. ', null, null, null);
INSERT INTO `book` VALUES ('308', '计算机原理及编程基础', '张勇', '[1] 金King. 吕秀锋译. C语言程序设计现代方法[M]. 人民邮电出版社出版, 2007.', null, null, null);
INSERT INTO `book` VALUES ('309', '计算机原理及编程基础', '张勇', '[2]Sara Ford. Microsoft Visual Studio Tips[M]. Microsoft Press, 2008.', null, null, null);
INSERT INTO `book` VALUES ('310', '计算机原理及编程基础', '张勇', '[3]Sara Ford.Visual Studio程序员箴言[M]. 人民邮电出版社出版, 2010.', null, null, null);
INSERT INTO `book` VALUES ('311', '计算机原理及编程基础', '张勇', '[4]Stephen Prata. C Primer Plus[M]. 人民邮电出版社出版, 2012.', null, null, null);
INSERT INTO `book` VALUES ('312', '计算机原理及编程基础', '张勇', '[5]MatthewCampbell. 景丽译.Object-C开发范例代码大全[M].清华大学出版社, 2013.', null, null, null);
INSERT INTO `book` VALUES ('313', '4D技术与应用', '胡庆武', '[1]自编教材《3D技术与应用》', null, null, null);
INSERT INTO `book` VALUES ('314', '4D技术与应用', '胡庆武', '[2]秦文虎,狄岚,姚晓峰,陈伟琦. 虚拟现实基础及可视化设计[M]. 化学工业, 2009.', null, null, null);
INSERT INTO `book` VALUES ('315', '4D技术与应用', '胡庆武', '[3]胡庆武. 地理调查与编码[M]. 武汉大学出版社, 2015.', null, null, null);
INSERT INTO `book` VALUES ('316', '4D技术与应用', '胡庆武', '[4]赖旭东. 机载激光雷达基础原理与应用[M]. 电子工业出版社, 2010.', null, null, null);
INSERT INTO `book` VALUES ('317', '4D技术与应用', '胡庆武', '[5]谢宏全. 地面三维激光扫描技术与工程应用[M]. 武汉大学出版社, 2013.', null, null, null);
INSERT INTO `book` VALUES ('318', '4D技术与应用', '胡庆武', '[6]张祖勋,张剑清. 数字摄影测量学[M]. 武汉大学, 2006.', null, null, null);
INSERT INTO `book` VALUES ('319', '4D技术与应用', '胡庆武', '[7]段延松. 数字摄影测量4D生产综合实习教程[M]. 武汉大学出版社, 2014.', null, null, null);
INSERT INTO `book` VALUES ('320', '4D技术与应用', '胡庆武', '[8]张飞舟. 智慧城市及其解决方案[M]. 电子工业出版社, 2015.', null, null, null);
INSERT INTO `book` VALUES ('321', '4D技术与应用', '胡庆武', '[9]王津红. BIM建筑设计实例[M]. 中国建筑工业出版社, 2013.', null, null, null);
INSERT INTO `book` VALUES ('322', 'Selected Topics in Remote Sensing and Information Engineering', '何涛', '[1]John R. Jensen. Remote Sensing of the Environment: An Earth Resource Perspective (2nd Edition). Pearson Education, Inc, 2007. ', null, null, null);
INSERT INTO `book` VALUES ('323', 'Selected Topics in Remote Sensing and Information Engineering', '何涛', '[2]W.G.Rees. Physical Principles of Remote Sensing, Second Edition. Cambridge University Press, 2001. ', null, null, null);
INSERT INTO `book` VALUES ('324', 'Selected Topics in Remote Sensing and Information Engineering', '何涛', '', null, null, null);
INSERT INTO `book` VALUES ('325', 'Selected Topics in Remote Sensing and Information Engineering', '何涛', '[3]Paul A. Longley,Michael F. Goodchild,David J. Maguire and David W. Rhind. Geographical Information Systems and Science (4th Edition). John Wiley & Sons, Inc, 2015. ', null, null, null);
INSERT INTO `book` VALUES ('326', '普通测量学', '付建红', '[1]潘正风等. 数字地形测量学. 武汉大学出版社, 2015. ', null, null, null);
INSERT INTO `book` VALUES ('327', '普通测量学', '付建红', '[2]武汉测绘科技大学《测量学》编写组. 测量学. 测绘出版社, 1994. ', null, null, null);
INSERT INTO `book` VALUES ('328', '遥感综合实习', '李刚', '[1]李刚. 遥感综合应用实践. 武汉大学出版社, 2018. ', null, null, null);
INSERT INTO `book` VALUES ('329', '遥感综合实习', '李刚', '[2]孙家?m. 遥感原理与应用. 武汉大学出版社, 2003. ', null, null, null);
INSERT INTO `book` VALUES ('330', '空间信息数字工程综合实习', '涂建光', '[1]陈永刚. 开源GIS与空间数据库实战教程. 清华大学出版社, 2016. ', null, null, null);
INSERT INTO `book` VALUES ('331', '空间信息数字工程综合实习', '涂建光', '[2]谬勇. Stuct2+Spring3+Hibernate框架技术精讲与整合案例[M].清华大学出版社，2015', null, null, null);
INSERT INTO `book` VALUES ('332', '空间信息数字工程综合实习', '涂建光', '[3]杨开振. JavaEE互联网轻量级框架整合开发SSM框架和Redis实现[M].电子工业出版社，2017', null, null, null);
INSERT INTO `book` VALUES ('333', '空间信息数字工程综合实习', '涂建光', '[4]埃里克?马瑟斯Eric Matthes. Python编程从入门到实践[M]. 人民邮电出版社, 2016.', null, null, null);
INSERT INTO `book` VALUES ('334', '空间信息数字工程综合实习', '涂建光', '[5](美)霍多罗夫. MongoDB权威指南[M]. 人民邮电出版社, 2016.', null, null, null);
INSERT INTO `book` VALUES ('335', '空间信息数字工程综合实习', '涂建光', '[6](美)汤姆?怀特(Tom White). Hadoop权威指南第4版[M].清华大学出版社, 2017.', null, null, null);
INSERT INTO `book` VALUES ('336', '空间信息数字工程综合实习', '涂建光', '[7]牟乃夏. ArcGIS10 地理信息系统教程??从初学到精通[M]. 测绘出版社, 2012.', null, null, null);
INSERT INTO `book` VALUES ('337', '空间信息数字工程综合实习', '涂建光', '[8]郭明强. WebGIS之OpenLayer全面解析[M]. 电子工业出版社, 2016.', null, null, null);
INSERT INTO `book` VALUES ('338', '空间信息数字工程综合实习', '涂建光', '[9]党安荣. Erads IMAGINE 遥感图像处理教程[M]. 清华大学出版社, 2010.', null, null, null);
INSERT INTO `book` VALUES ('339', '面向对象的程序设计', '段延松', '[1]龚晓庆. C++面向对象程序设计[M]. 清华大学出版社, 2011.', null, null, null);
INSERT INTO `book` VALUES ('340', '面向对象的程序设计', '段延松', '[2]Sara Ford. Microsoft Visual Studio Tips[M]. Microsoft Press, 2008.', null, null, null);
INSERT INTO `book` VALUES ('341', '面向对象的程序设计', '段延松', '[3]Sara Ford.Visual Studio程序员箴言[M]. 人民邮电出版社出版, 2010.', null, null, null);
INSERT INTO `book` VALUES ('342', '面向对象的程序设计', '段延松', '[4]Kayshav Dattatri. C++面向对象高效编程（第二版） [M].人民邮电出版社出版, 2013.', null, null, null);
INSERT INTO `book` VALUES ('343', '面向对象的程序设计', '段延松', '[5]Stephen Prata. C Primer Plus[M]. 人民邮电出版社出版, 2012.', null, null, null);
INSERT INTO `book` VALUES ('344', '面向对象的程序设计', '段延松', '[6]MatthewCampbell. 景丽译.Object-C开发范例代码大全[M]. 清华大学出版社, 2013.', null, null, null);
INSERT INTO `book` VALUES ('345', 'Python与R语言编程', '卢宾宾', '[1]卢宾宾. R语言空间数据处理与分析实践教程. 武汉大学出版社, 出版中。', null, null, null);
INSERT INTO `book` VALUES ('346', 'Python与R语言编程', '卢宾宾', '[2]卢宾宾. Python语言空间数据处理与分析实践教程. 武汉大学出版社, 出版中。', null, null, null);
INSERT INTO `book` VALUES ('347', 'Python与R语言编程', '卢宾宾', '[3]Bivand, R. S., Pebesma, E. J., & Gómez-Rubio, V. Applied Spatial Data Analysis with R. New York: Springer Science+Business Media, 2008.', null, null, null);
INSERT INTO `book` VALUES ('348', 'Python与R语言编程', '卢宾宾', '[4]Bivand, R.. Spatial data in R. http://r-spatial.sourceforge.net/ (2007).', null, null, null);
INSERT INTO `book` VALUES ('349', 'Python与R语言编程', '卢宾宾', '[5]Michael Diener. Python Geospatial Analysis Cookbook. Packt Publishing Ltd, 2015.', null, null, null);
INSERT INTO `book` VALUES ('350', 'Spatial Statistics and Spatial Data Science', '卢宾宾', '[1]Noel A.C. Cressie. Statistics for spatial data, Revised version, John Wiley & Sons, Ltd., 1993.', null, null, null);
INSERT INTO `book` VALUES ('351', 'Spatial Statistics and Spatial Data Science', '卢宾宾', '[2]Daniel A. Griffith, Spatial autocorrelation and spatial filtering, Springer, 2010.', null, null, null);
INSERT INTO `book` VALUES ('352', 'Spatial Statistics and Spatial Data Science', '卢宾宾', '[3]Luc Anselin. Local indicators of spatial association?lisa. Geographical Analysis, 1995.', null, null, null);
INSERT INTO `book` VALUES ('353', 'Spatial Statistics and Spatial Data Science', '卢宾宾', '[4]Fotheringham, A.S., C. Brunsdon, and M. Charlton, Geographically Weighted Regression: the analysis of spatially varying relationships. Chichester: Wiley, 2002.', null, null, null);
INSERT INTO `book` VALUES ('354', 'Spatial Statistics and Spatial Data Science', '卢宾宾', '[5]Gollini, I., Lu, B., Charlton, M., Brunsdon, C., & Harris, P.. GWmodel: an R Package for Exploring Spatial Heterogeneity using Geographically Weighted Models. Journal of Statistical Software, 2015.', null, null, null);
INSERT INTO `book` VALUES ('355', 'Spatial Statistics and Spatial Data Science', '卢宾宾', '[6]Lu, B., Harris, P., Charlton, M., & Brunsdon, C. (2014). The GWmodel R package: further topics for exploring spatial heterogeneity using geographically weighted models. Geo-Spatial Information Science, 17, 85-101.', null, null, null);
INSERT INTO `book` VALUES ('356', '软件工程', '江聪世', '[1]窦万峰. 软件工程及实践. 电子工业出版社, 2011. ', null, null, null);
INSERT INTO `book` VALUES ('357', '软件工程', '江聪世', '[2]窦万峰. 软件工程实验教程. 机械工业出版社, 2015.', null, null, null);
INSERT INTO `book` VALUES ('358', '软件工程', '江聪世', '[3]Stephen R.Schach. 面向对象与经典软件工程Object-Oriented and Classical Software Engineering__8th. 机械工业出版社, 2003.', null, null, null);
INSERT INTO `book` VALUES ('359', '软件工程', '江聪世', '[4]秦小波. 设计模式之禅. 机械工业出版社, 2018. ', null, null, null);
INSERT INTO `book` VALUES ('360', '环境保护与规划', '万幼川', '[1]何强. 环境学导论（第二版）. 清华大学出版社, 1994. ', null, null, null);
INSERT INTO `book` VALUES ('361', '环境保护与规划', '万幼川', '[2]郭怀成等. 环境规划学. 高等教育出版社, 2001. ', null, null, null);
INSERT INTO `book` VALUES ('362', '环境保护与规划', '万幼川', '[3]卓正大等. 生态系统. 高等教育出版社, 1991. ', null, null, null);
INSERT INTO `book` VALUES ('363', '环境保护与规划', '万幼川', '[4]唐永鉴等. 大气环境学. 中山大学出版社, 1988. ', null, null, null);
INSERT INTO `book` VALUES ('364', '环境保护与规划', '万幼川', '[5]傅国伟. 河流水质数学模型及其模拟计算. 清中国环境科学出版社, 1987. ', null, null, null);
INSERT INTO `book` VALUES ('365', '环境保护与规划', '万幼川', '[6]肖庭延等. 华中科技大学出版社. 清华大学出版社, 1993. ', null, null, null);
INSERT INTO `book` VALUES ('366', '自然地理', '唐雪华', '[1]伍光和等. 自然地理学（第三版）. 高等教育出版社, 2000. ', null, null, null);
INSERT INTO `book` VALUES ('367', '自然地理', '唐雪华', '[2]伍光和等. 综合自然地理学（第二版）. 高等教育出版社, 2004. ', null, null, null);
INSERT INTO `book` VALUES ('368', '自然地理', '唐雪华', '[3]陈静生等. 地学基础（第一版）. 高等教育出版社, 2001. ', null, null, null);
INSERT INTO `book` VALUES ('369', '自然地理', '唐雪华', '[4]金祖孟等. 地球概论（第三版）. 高等教育出版社, 1997. ', null, null, null);
INSERT INTO `book` VALUES ('370', 'GNSS原理及应用', '陈智勇', '[1]李征航,黄劲松. GPS测量与数据处理. 武汉大学出版社, 2016. ', null, null, null);
INSERT INTO `book` VALUES ('371', 'GNSS原理及应用', '陈智勇', '[2]李天文. GPS测量原理及应用. 科学出版社, 2015. ', null, null, null);
INSERT INTO `book` VALUES ('372', 'Comprehensive Applications of National Geo-Information', '肖锐', '[1]Michael Zeiler. Modeling Our World[M]. Environmental Systems Research Institute, Inc，US., 1999', null, null, null);
INSERT INTO `book` VALUES ('373', 'Comprehensive Applications of National Geo-Information', '肖锐', '[2]Rui Xiao, Diwei Jiang, George Christakos, Xufeng Fei, Jiaping Wu. Soil Landscape Pattern Changes in Response to Rural Anthropogenic Activity across Tiaoxi Watershed, China. PLoS ONE, 2016.', null, null, null);
INSERT INTO `book` VALUES ('374', 'Comprehensive Applications of National Geo-Information', '肖锐', '[3]Rui Xiao, Guofeng Wang, Meng Wang. Transportation disadvantage and neighborhood sociodemographics: A composite indicator approach to examining social inequalities. Social Indicators Research, 2017.', null, null, null);
INSERT INTO `book` VALUES ('375', 'Comprehensive Applications of National Geo-Information', '肖锐', '[4]Rui Xiao, Guofeng Wang, Qianwen Zhang, Zhonghao Zhang. Multi-scale analysis of relationship between landscape pattern and urban river water quality in different seasons. Scientific Reports, 2016.', null, null, null);
INSERT INTO `book` VALUES ('376', 'Comprehensive Applications of National Geo-Information', '肖锐', '[5]Tao Jia, Kai Chen, Jiye Wang. Characterizing the Growth Patterns of 45 Major Metropolitans in Mainland China Using DMSP/OLS Data [J]. Remote Sensing, 2017.', null, null, null);
INSERT INTO `book` VALUES ('377', 'GIS应用', '王少华', '[1]陈永刚. 开源GIS与空间数据库实战教程. 清华大学出版社, 2016. ', null, null, null);
INSERT INTO `book` VALUES ('378', 'GIS应用', '王少华', '[2]刘建国.  考古测绘、遥感与GIS[M]. 北京大学出版社, 2008.', null, null, null);
INSERT INTO `book` VALUES ('379', 'GIS应用', '王少华', '[3]刘建国. 考古与地理信息系统[M]. 科学出版社, 2010.', null, null, null);
INSERT INTO `book` VALUES ('380', 'GIS应用', '王少华', '[4]周明全,耿国华,武仲科. 文化遗产数字化保护技术及应用，高等教育出版社，2011', null, null, null);
INSERT INTO `book` VALUES ('381', 'GIS应用', '王少华', '[5]赵云,王少华,严绍军,王?? 文化遗产数字化展示研究[M]. 中国地质大学出版社, 2016.', null, null, null);
INSERT INTO `book` VALUES ('382', 'GIS应用', '王少华', '[6]郑巨欣,陈峰. 文化遗产保护的数字化展示与传播[M]. 学苑出版社, 2011.', null, null, null);
INSERT INTO `book` VALUES ('383', 'GIS应用', '王少华', '[7]李建松,唐雪华. 地理信息系统原理[M]. 武汉大学出版社，2015.', null, null, null);
INSERT INTO `book` VALUES ('384', 'GIS应用', '王少华', '[8]边馥苓. 空间信息导论. 测绘出版社，2006.', null, null, null);
INSERT INTO `book` VALUES ('385', 'GIS应用', '王少华', '[9]边馥苓. 数字工程的原理与方法. 测绘出版社，2011.', null, null, null);
INSERT INTO `book` VALUES ('386', '数字工程软件架构', '熊庆文', '[1] 张友生. 软件架构原理. 清华大学出版社, 2014. ', null, null, null);
INSERT INTO `book` VALUES ('387', '数字工程软件架构', '熊庆文', '[1] 李金刚等. 软件架构理论及应用. 清华大学出版社, 2013. ', null, null, null);
INSERT INTO `book` VALUES ('388', '数字工程软件架构', '熊庆文', '[1] 张春祥等. 软件架构理论与实践. 中国电力出版社, 2011. ', null, null, null);
INSERT INTO `book` VALUES ('389', '数字工程软件架构', '熊庆文', '[1] 余雪丽. 软件架构及实例分析. 科学出版社, 2004. ', null, null, null);
INSERT INTO `book` VALUES ('390', 'Matlab编程', '张熠', '[1]周建兴,岂兴明等. Matlab从入门到精通. 人民邮电出版社, 2008. ', null, null, null);
INSERT INTO `book` VALUES ('391', 'Matlab编程', '张熠', '[2]Holly Moor著,高会生等译. Matlab实用教程（第二版）.', null, null, null);
INSERT INTO `book` VALUES ('392', 'Matlab编程', '张熠', '', null, null, null);
INSERT INTO `book` VALUES ('393', '高光谱遥感', '周颖', '[1]张良培,张立福. 高光谱遥感[M]. 测绘出版社, 2011.', null, null, null);
INSERT INTO `book` VALUES ('394', '高光谱遥感', '周颖', '[2]浦瑞良, 宫鹏. 高光谱遥感及其应用[M]. 高等教育出版社, 2003.', null, null, null);
INSERT INTO `book` VALUES ('395', '高光谱遥感', '周颖', '[3]童庆禧, 张兵, 郑兰芬. 高光谱遥感[M]. 高等教育出版社, 2006.', null, null, null);
INSERT INTO `book` VALUES ('396', '高光谱遥感', '周颖', '[4]赵春晖, 王立国, 齐滨. 高光谱遥感图像处理方法及其应用[M]. 电子工业出版社, 2016.', null, null, null);
INSERT INTO `book` VALUES ('397', '高光谱遥感', '周颖', '[5]Chang C I. Hyperspectral Data Exploitation: Theory and Applications[M]. Wiley-Interscience, 2007.', null, null, null);
INSERT INTO `book` VALUES ('398', '地理国情监测部门实习', '李建松', '实习内容涉及地理国情监测全过程。具体内容由实习单位根据具体情况确定。', null, null, null);
INSERT INTO `book` VALUES ('399', '地理国情监测部门实习', '李建松', '实习形式为到生产单位参与具体工作。', null, null, null);
INSERT INTO `book` VALUES ('400', '航空与航天摄影', '孙和利', '[1]乔瑞亭、孙和利、李欣. 摄影与空中摄影, 武汉: 武汉大学出版社, 2007.', null, null, null);
INSERT INTO `book` VALUES ('401', '航空与航天摄影', '孙和利', '[2]宣家斌. 航空与航天摄影技术. 北京: 测绘出版社, 1992. ', null, null, null);
INSERT INTO `book` VALUES ('402', '航空与航天摄影', '孙和利', '[3]颜志刚. 摄影技艺教程(第六版). 上海: 复旦大学出版社, 2009.', null, null, null);
INSERT INTO `book` VALUES ('403', '航空与航天摄影', '孙和利', '[4]廖延彪. 成像光学导论[M]. 清华大学出版社, 2008.', null, null, null);
INSERT INTO `book` VALUES ('404', '遥感原理与方法课程设计', '李刚', '[1]杨枝灵,王开等. Visual C++数字图像获取、处理及其实践应用. 人民邮电出版社, 2003. ', null, null, null);
INSERT INTO `book` VALUES ('405', '遥感原理与方法课程设计', '李刚', '[2]孙家?m. 遥感原理与应用. 武汉大学出版社, 2003. ', null, null, null);
INSERT INTO `book` VALUES ('406', '土地管理与地籍测量', '周军其', '[1]陆红生. 土地管理学总论（第六版）. 中国农业出版社，2006.', null, null, null);
INSERT INTO `book` VALUES ('407', '土地管理与地籍测量', '周军其', '[2]詹长根. 地籍测量学（第二版）. 武汉大学出版社，2005.', null, null, null);
INSERT INTO `book` VALUES ('408', '土地管理与地籍测量', '周军其', '[3]刘胜华,刘家彬. 土地管理概论（第一版）. 武汉大学出版社，2005.', null, null, null);
INSERT INTO `book` VALUES ('409', '土地管理与地籍测量', '周军其', '[4]张正峰. 土地资源管理学（第一版）.中国人民大学出版社，2008.', null, null, null);
INSERT INTO `book` VALUES ('410', '土地管理与地籍测量', '周军其', '[5]樊志全. 地籍调查（第一版）.中国农业出版社，2004.', null, null, null);
INSERT INTO `book` VALUES ('411', '遥感图像解译', '周军其', '[1]关泽群，刘继琳.遥感图像解译[M]. 武汉大学出版社，2007.', null, null, null);
INSERT INTO `book` VALUES ('412', '遥感图像解译', '周军其', '[1]A.H.日维钦.航空摄影象片判读（第一版）[M]. 测绘出版社，1988.', null, null, null);
INSERT INTO `book` VALUES ('413', '遥感图像解译', '周军其', '[2]濮静娟. 遥感图像目视解译原理与方法（第一版）[M]. 中国科学技术出版社，1992.', null, null, null);
INSERT INTO `book` VALUES ('414', '遥感图像解译', '周军其', '[3]T.M.Lillesand, R. W. Kiefer. Remote Sensing and Image Interpretation[M]. New York: John Wiley and Sons Inc., 1994.', null, null, null);
INSERT INTO `book` VALUES ('415', '遥感图像解译', '周军其', '[4]黄昕. 高分辨率遥感信息处理[M]. 科学出版社，2018.', null, null, null);
INSERT INTO `book` VALUES ('416', '遥感传感器原理', '张熠', '[1] Charles Elachi,  Jakob van zyl. John Wiley & Sons, Inc. Introduction to the physics and techniques of remote sensing. Second edition. Hoboken, New Jersey, 2006.', null, null, null);
INSERT INTO `book` VALUES ('417', '遥感传感器原理', '张熠', '[2]W.G.Rees. Physical Principles of Remote Sensing, Second Edition. Cambridge University Press, 2001.', null, null, null);
INSERT INTO `book` VALUES ('418', '遥感传感器原理', '张熠', '[3]马文坡. 航天光学遥感技术(空间飞行器设计专业系列教材)[M]. 中国科学技术出版社, 2011.', null, null, null);
INSERT INTO `book` VALUES ('419', '遥感传感器原理', '张熠', '[4]梅安新等. 遥感导论[M]. 高等教育出版社, 2001.', null, null, null);
INSERT INTO `book` VALUES ('420', '遥感传感器原理', '张熠', '[5]张庸. 遥感成像原理及图像特征[M]. 地质出版社, 1994.', null, null, null);
INSERT INTO `book` VALUES ('421', '遥感传感器原理', '张熠', '[6]廖延彪. 成像光学导论[M]. 清华大学出版社, 2008.', null, null, null);
INSERT INTO `book` VALUES ('422', '遥感传感器原理', '张熠', '[7]韩心志. 航天光学遥感辐射度学[M]. 哈尔滨工业大学出版社,1994.', null, null, null);
INSERT INTO `book` VALUES ('423', '信号处理与分析', '崔卫红', '[1]徐科军. 信号分析与处理(第二版). 清华大学出版社, 2012. ', null, null, null);
INSERT INTO `book` VALUES ('424', '信号处理与分析', '崔卫红', '[2]赵光宙. 信号分析与处理. 机械工业出版社, 2006. ', null, null, null);
INSERT INTO `book` VALUES ('425', '信号处理与分析', '崔卫红', '[3]郑君里,应启珩,杨为理. 信号与系统（第二版 上、下）. 高等教育出版社, 2016. ', null, null, null);
INSERT INTO `book` VALUES ('426', '信号处理与分析', '崔卫红', '[4]姜建国,曹建中,高玉明. 信号与系统分析基础（第2版）. 清华大学出版社, 2006. ', null, null, null);
INSERT INTO `book` VALUES ('427', '信号处理与分析', '崔卫红', '[5]肖志涛. 开信号与系统--连续与离散（第四版）. 电子工业出版社出版, 2005. ', null, null, null);
INSERT INTO `book` VALUES ('428', '信号处理与分析', '崔卫红', '[6]程佩青. 数字信号处理教程（第二版）. 清华大学出版社, 2001. ', null, null, null);
INSERT INTO `book` VALUES ('429', '信号处理与分析', '崔卫红', '[7]胡广书. 数字信号处理－理论、算法与实现（第二版）. 清华大学出版社, 2003. ', null, null, null);
INSERT INTO `book` VALUES ('430', '遥感应用模型', '彭漪', '[1]John R. Jensen. Remote Sensing of the Environment: An Earth Resource Perspective (2nd Edition). Pearson Education, Inc, 2007. ', null, null, null);
INSERT INTO `book` VALUES ('431', '遥感应用模型', '彭漪', '[2]李小文,王锦地等. 定量遥感. 科学出版社, 2012. ', null, null, null);
INSERT INTO `book` VALUES ('432', '地理国情分析与建模', '陈江平', '[1]James E. Elementary Statistics for geographers. the Guilford press, 2009.', null, null, null);
INSERT INTO `book` VALUES ('433', '地理国情分析与建模', '陈江平', '[2]韦玉春. 地理建模的原理与方法. 科学出版社, 2005.', null, null, null);
INSERT INTO `book` VALUES ('434', '地理国情分析与建模', '陈江平', '[3]徐建华. 现代地理学中的数学方法. 高等教育出版社, 1994.', null, null, null);
INSERT INTO `book` VALUES ('435', '地理国情分析与建模', '陈江平', '[4]张超,杨秉赓. 计量地理学基础. 高等教育出版社, 1991.', null, null, null);
INSERT INTO `book` VALUES ('436', '地理国情分析与建模', '陈江平', '[5]刘昌明,岳天祥,周成虎. 地理学的数学模型与应用. 科学出版社, 2000.', null, null, null);
INSERT INTO `book` VALUES ('437', '地理国情分析与建模', '陈江平', '[6]陈彦光. 地理数学方法：基础和应用. 科学出版社, 2010.', null, null, null);
INSERT INTO `book` VALUES ('438', '测绘地理信息法律法规', '周军其', '[1]测绘管理与法律法规. 测绘出版社, 2018. ', null, null, null);
INSERT INTO `book` VALUES ('439', '传感器网络课程设计', '邬建伟', '[1]崔逊学,左丛菊. 无线传感器网络简明教程. 清华大学出版社, 2009.', null, null, null);
INSERT INTO `book` VALUES ('440', '传感器网络课程设计', '邬建伟', '[2]CVT-WSN-ST综合教学实验平台物联网实验手册. 武汉创维特信息技术有限公司, 2016.', null, null, null);
INSERT INTO `book` VALUES ('441', '地表覆盖与土地利用', '孙和利', '[1]自编教材.地表覆盖与土地利用课程小组编写.', null, null, null);
INSERT INTO `book` VALUES ('442', '地表覆盖与土地利用', '孙和利', '[2]宫攀等.中国土地覆盖分类研究. 经济科学出版社,2013.', null, null, null);
INSERT INTO `book` VALUES ('443', '地表覆盖与土地利用', '孙和利', '[3]李月臣等.中国北方土地利用覆盖变化问题研究.重庆大学出版社,2008.', null, null, null);
INSERT INTO `book` VALUES ('444', '地表覆盖与土地利用', '孙和利', '[4]唐华俊等.中国土地利用/土地覆盖变化研究. 中国农业科学技术出版社, 2004.', null, null, null);
INSERT INTO `book` VALUES ('445', '地表覆盖与土地利用', '孙和利', '[5]吴建平等. 区域土地利用土地覆盖遥感调查.华东师范大学出版社, 1999.', null, null, null);
INSERT INTO `book` VALUES ('446', '地理变化检测与分析', '赖旭东', '[1]自编教材.待出版.', null, null, null);
INSERT INTO `book` VALUES ('447', '地理变化检测与分析', '赖旭东', '[2]李德仁. 利用遥感影像进行变化检测[J]. 武汉大学学报(信息科学版). 2003, 28(特刊):7-12', null, null, null);
INSERT INTO `book` VALUES ('448', '地理变化检测与分析', '赖旭东', '[3]周启鸣. 多时相遥感影像变化检测综述[J]. 国际摄影测量与遥感动态, 2010, 6:1?8', null, null, null);
INSERT INTO `book` VALUES ('449', '地理变化检测与分析', '赖旭东', '[4]张良培，武辰. 多时相遥感影像变化检测的现状与展望[J]. 遥感学报. 2017, 46(10):1447-1459', null, null, null);
INSERT INTO `book` VALUES ('450', '地理变化检测与分析', '赖旭东', '[5]地理国情监测研究与探索[M].中国测绘宣传中心编. 北京: 测绘出版社，2011.', null, null, null);
INSERT INTO `book` VALUES ('451', '地理变化检测与分析', '赖旭东', '[6]张晓东.遥感影像变化检测[M]. 武汉大学出版社，2015.', null, null, null);
INSERT INTO `book` VALUES ('452', '地理国情专题制图与可视化', '余洋', '[1]自编教材.待出版.', null, null, null);
INSERT INTO `book` VALUES ('453', '地理国情专题制图与可视化', '余洋', '[2]何宗宜. 计算机地图制图. 测绘出版社, 2008.', null, null, null);
INSERT INTO `book` VALUES ('454', '地理国情专题制图与可视化', '余洋', '[3]周园. 地图与地图制图.测绘出版社，2011.', null, null, null);
INSERT INTO `book` VALUES ('455', '地理国情专题制图与可视化', '余洋', '[4]王明孝,张志华,杨维芳. 地理空间数据可视化. 科学出版社，2012. ', null, null, null);
INSERT INTO `book` VALUES ('456', '地理国情专题制图与可视化', '余洋', '[5]李霖,应申,朱海红. 地理计算原理与方法. 测绘出版社，2008.', null, null, null);
INSERT INTO `book` VALUES ('457', '地理国情专题制图与可视化', '余洋', '[6]王铮,吴静编. 计算地理学. 科学出版社, 2011.', null, null, null);
INSERT INTO `book` VALUES ('458', '地理国情专题制图与可视化', '余洋', '[7]陈为,沈则潜,陶煜波. 数据可视化. 电子工业出版社, 2013.', null, null, null);
INSERT INTO `book` VALUES ('459', '地理国情监测与应用', '姚春静', '[1]自编教材. 地理国情监测与应用课程小组编写.', null, null, null);
INSERT INTO `book` VALUES ('460', '地理国情监测与应用', '姚春静', '[1]张安定等. 遥感技术基础与应用. 科学出版社,2014.', null, null, null);
INSERT INTO `book` VALUES ('461', '地理国情监测与应用', '姚春静', '[2]浦瑞良等. 高光谱遥感及其应用. 高等教育出版社,2003.', null, null, null);
INSERT INTO `book` VALUES ('462', '地理国情监测与应用', '姚春静', '[3]白淑英等. 农业遥感. 科学出版社, 2013.', null, null, null);
INSERT INTO `book` VALUES ('463', '地理国情监测与应用', '姚春静', '[4]Gert A. Schultz等,韩敏（译）. 水文与水管理中的遥感技术. 中国水利水电出版社, 2006.', null, null, null);
INSERT INTO `book` VALUES ('464', '地理监测原理与方法', '卢宾宾', '[1]李建松,周军其. 地理监测原理. 武汉大学出版社，2014', null, null, null);
INSERT INTO `book` VALUES ('465', '地理监测原理与方法', '卢宾宾', '[2]史文中. 地理国情监测理论与技术. 科学出版社，2015.', null, null, null);
INSERT INTO `book` VALUES ('466', '传感器网络', '邬建伟', '[1]彭力. 无线传感器网络原理与应用.西安电子科技大学出版社，2015.', null, null, null);
INSERT INTO `book` VALUES ('467', '传感器网络', '邬建伟', '[2]自编教材.', null, null, null);
INSERT INTO `book` VALUES ('468', '传感器网络', '邬建伟', '[3]崔逊学，左从菊. 无线传感器网络简明教程（第2版）. 清华大学出版社, 2015.', null, null, null);
INSERT INTO `book` VALUES ('469', '传感器网络', '邬建伟', '[4]谭励. 无线传感器网络理论与技术应用.机械工业出版社,  2011.', null, null, null);
INSERT INTO `book` VALUES ('470', '传感器网络', '邬建伟', '[5]杜军朝,刘惠,刘传益,马海潮等. ZigBee技术原理与实战. 机械工业出版社, 2015.', null, null, null);
INSERT INTO `book` VALUES ('471', '传感器网络', '邬建伟', '[6]王小强,欧阳骏,黄宁淋.  ZigBee无线传感器网络设计与实现. 化学工业出版社，2012.', null, null, null);
INSERT INTO `book` VALUES ('472', '传感器网络', '邬建伟', '[7]邱铁,夏锋,周玉. STM32W108嵌入式无线传感器. 清华大学出版社, 2014.', null, null, null);
INSERT INTO `book` VALUES ('473', '走进遥感世界??遥感技术系列实验', '季铮', '[1]孙家?m等. 遥感原理与应用. 武汉大学出版社，2003.', null, null, null);
INSERT INTO `book` VALUES ('474', '走进遥感世界??遥感技术系列实验', '季铮', '[2]关泽群,刘继琳. 遥感图像解译. 武汉大学出版社，2006.', null, null, null);
INSERT INTO `book` VALUES ('475', '走进遥感世界??遥感技术系列实验', '季铮', '[3]张祖勋,张剑清等. 数字摄影测量学. 武汉大学出版社，2012.', null, null, null);
INSERT INTO `book` VALUES ('476', '走进遥感世界??遥感技术系列实验', '季铮', '[4]张剑清,潘励,王树根. 摄影测量学. 武汉大学出版社，2003.', null, null, null);
INSERT INTO `book` VALUES ('477', '走进遥感世界??遥感技术系列实验', '季铮', '[5]韩鹏,徐占华等. 地理信息系统开发??ArcObjects方法.武汉大学出版社，2005.', null, null, null);
INSERT INTO `book` VALUES ('478', '走进遥感世界??遥感技术系列实验', '季铮', '[6]《Erdas软件使用说明》', null, null, null);
INSERT INTO `book` VALUES ('479', '走进遥感世界??遥感技术系列实验', '季铮', '[7]《ArcGIS软件及二次开发相关资料》', null, null, null);
INSERT INTO `book` VALUES ('480', '走进遥感世界??遥感技术系列实验', '季铮', '[8]《VirtuoZo操作手册》', null, null, null);
INSERT INTO `book` VALUES ('481', '无人机遥感', '季铮', '[1]孙家?m等. 遥感原理与应用. 武汉大学出版社，2003.', null, null, null);
INSERT INTO `book` VALUES ('482', '无人机遥感', '季铮', '[2]张祖勋,张剑清等. 数字摄影测量学. 武汉大学出版社，2012.', null, null, null);
INSERT INTO `book` VALUES ('483', '无人机遥感', '季铮', '[3]万刚. 无人机测绘技术与应用. 测绘出版社，2015.', null, null, null);
INSERT INTO `book` VALUES ('484', '无人机遥感', '季铮', '[4]宇辰网. 无人机：引领空中机器人新革命. 机械工业出版社，2017.', null, null, null);
INSERT INTO `book` VALUES ('485', '遥感技术应用及发展', '龚??', '[1]孙家?m,倪玲,周军其等. 遥感原理与应用（第三版）.武汉大学出版社,  2003.', null, null, null);
INSERT INTO `book` VALUES ('486', '遥感技术应用及发展', '龚??', '[2]赵英时. 遥感应用分析原理与方法（第一版）.科学出版社, 2003.', null, null, null);
INSERT INTO `book` VALUES ('487', '遥感技术应用及发展', '龚??', '[3]村井. 遥感精解. 测绘出版社，1993.', null, null, null);
INSERT INTO `book` VALUES ('488', '遥感技术应用及发展', '龚??', '[4]周成虎等. 遥感影像地学理解与分析. 科学出版社. ', null, null, null);
INSERT INTO `book` VALUES ('489', '遥感技术应用及发展', '龚??', '[5]徐希孺. 遥感物. 北大出版社.', null, null, null);
INSERT INTO `book` VALUES ('490', '遥感技术应用及发展', '龚??', '[6]《Field guide》（ERDAS的帮助文件）', null, null, null);
INSERT INTO `book` VALUES ('491', '地理学概论', '马吉平', '[1]王铮. 普通地理学[M]. 科学出版社, 2010.', null, null, null);
INSERT INTO `book` VALUES ('492', '地理学概论', '马吉平', '参考书：', null, null, null);
INSERT INTO `book` VALUES ('493', '地理学概论', '马吉平', '[2]白光润. 地理科学导论[M]. 高等教育出版社, 2006.', null, null, null);
INSERT INTO `book` VALUES ('494', '地理学概论', '马吉平', '[3]伍光和. 综合自然地理学[M]. 高等教育出版社,2004.', null, null, null);
INSERT INTO `book` VALUES ('495', '地理学概论', '马吉平', '[4]李小建. 经济地理 [M]. 高等教育出版社, 2006.', null, null, null);
INSERT INTO `book` VALUES ('496', '地理学概论', '马吉平', '[5]赵荣.人文地理学[M]. 高等教育出版社,2001', null, null, null);
INSERT INTO `book` VALUES ('497', '生产实践E (服务学习)', '李建松', '实习地点：生产或科研单位。', null, null, null);
INSERT INTO `book` VALUES ('498', '生产实践E (服务学习)', '李建松', '实习方式：校内指定导师，生产或科研单位也指定一位导师，学生参与生产单位的具体工作。', null, null, null);
INSERT INTO `book` VALUES ('499', '地理国情监测综合实习', '周军其', '地理国情监测有关的教材和论文，鼓励大家利用网络检索需要的资料（如相关学术论文）。', null, null, null);
INSERT INTO `book` VALUES ('500', '生产实践（服务学习）', '陈江平', '[1]自编教材.待出版.', null, null, null);
INSERT INTO `book` VALUES ('501', '生产实践（服务学习）', '陈江平', '[2]Cress, C.M., P.J. Collier, & V. L. Reitenauer. Learning Through Serving: A Student Guidebook for Service-Learning Across the Disciplines. Stylus Publishing, 2005.', null, null, null);
INSERT INTO `book` VALUES ('502', '生产实践（服务学习）', '陈江平', '[3]Adams, M., W. Blumenfeld, C. R. Casta?eda, H.W. Hackman, M. L. Peters, X. Zú?iga. (Ed.) Readings for Diversity and Social Justice, 2nd ed., UK: Routledge, 2010.', null, null, null);
INSERT INTO `book` VALUES ('503', '生产实践（服务学习）', '陈江平', '[4]Sen, A.K.. The Idea of Justice. Harvard University Press, 2009.', null, null, null);
INSERT INTO `book` VALUES ('504', '生产实践（服务学习）', '陈江平', '[5]Sandel, M.J.. Justice: What\'s the Right Thing to Do? Farrar, Straus and Giroux, 2009.', null, null, null);
INSERT INTO `book` VALUES ('505', '位置服务原理与应用', '熊庆文', '[1]A. Kupper. Location-Based Services.Wiley, 2005.', null, null, null);
INSERT INTO `book` VALUES ('506', '位置服务原理与应用', '熊庆文', '[1]Grewal,Weill and Andrews. Global Positioning Systems, Inertial Navigation, and Integration. Wiley, 2007.', null, null, null);
INSERT INTO `book` VALUES ('507', '位置服务原理与应用', '熊庆文', '[1]Kolodziej and Hjelm. Local Positioning Systems ?LBS Applications and Services. CRC Press, 2006.', null, null, null);
INSERT INTO `book` VALUES ('508', 'GIS综合实习', '张文', '[1]《GIS综合实习》实习指导书（自编）.', null, null, null);
INSERT INTO `book` VALUES ('509', 'GIS综合实习', '张文', '[2]池建. 精通ArcGIS地理信息系统. 清华大学出版社，2011.', null, null, null);
INSERT INTO `book` VALUES ('510', 'GIS综合实习', '张文', '[3]ArcGIS软件操作与应用》.科学出版社，王新生，2010.', null, null, null);
INSERT INTO `book` VALUES ('511', 'GIS综合实习', '张文', '[4]牟乃夏. ArcGIS Engine地理信息系统开发教程. 测绘出版社，2014.', null, null, null);
INSERT INTO `book` VALUES ('512', 'GIS综合实习', '张文', '[5]邱洪钢等. ArcGIS Engine地理信息系统开发从入门到精通（第二版）. 人民邮电出版社，2013.', null, null, null);
INSERT INTO `book` VALUES ('513', '信息系统集成与管理课程实习', '朱国宾', '[1]张家浩. 软件架构设计实践教程[M]. 清华大学出版社, 2014.', null, null, null);
INSERT INTO `book` VALUES ('514', '信息系统集成与管理课程实习', '朱国宾', '[2]Daniel J. Paulish. Architecture-Centric Software Project Management[M]. 清华大学出版社, 2003.', null, null, null);
INSERT INTO `book` VALUES ('515', '信息系统集成与管理课程实习', '朱国宾', '[3]巴斯等. 软件构架实践（英文影印版）. 清华大学出版社,  2013.', null, null, null);
INSERT INTO `book` VALUES ('516', '信息系统集成与管理课程实习', '朱国宾', '[4]Bob Hughes, Mike Cotterell. 廖彬山,周卫华译. 软件项目管理（第5版）. 机械工业出版社, 2015.', null, null, null);
INSERT INTO `book` VALUES ('517', '信息系统集成与管理', '朱国宾', '[1]张家浩. 软件架构设计实践教程[M]. 清华大学出版社, 2014.', null, null, null);
INSERT INTO `book` VALUES ('518', '信息系统集成与管理', '朱国宾', '[2]Daniel J. Paulish. Architecture-Centric Software Project Management[M]. 清华大学出版社, 2003.', null, null, null);
INSERT INTO `book` VALUES ('519', '信息系统集成与管理', '朱国宾', '[3]巴斯等. 软件构架实践（英文影印版）. 清华大学出版社,  2013.', null, null, null);
INSERT INTO `book` VALUES ('520', '信息系统集成与管理', '朱国宾', '[4]Thomas Erl, Zaigham Mahmood, Ricardo Puttini. Cloud Computing：Concepts，Technology & Architecture[M]. 机械工业出版社, 2014.', null, null, null);
INSERT INTO `book` VALUES ('521', '信息系统集成与管理', '朱国宾', '[5] Bob Hughes, Mike Cotterell. 廖彬山,周卫华译. 软件项目管理（第5版）. 机械工业出版社, 2015.', null, null, null);
INSERT INTO `book` VALUES ('522', '智慧城市与三维城市建模', '范红超', '[2] Gerhard Gr?ger, Thomas H. Kolbe, Claus Nagel, Karl-Heinz H?fele. 2012. OGC City Geography Markup Language (CityGML) Encoding Standard. OGC.', null, null, null);
INSERT INTO `book` VALUES ('523', '智慧城市与三维城市建模', '范红超', '[3] Web 3D, Information technology - Computer graphics and image processing - Extensible 3D (X3D). ISO/IEC 19775:2004. http://www.web3d.org/x3d/specifications/, 2004.', null, null, null);
INSERT INTO `book` VALUES ('524', '智慧城市与三维城市建模', '范红超', '[4] Cesium for 3D city visualization: https://cesium.com/', null, null, null);
INSERT INTO `book` VALUES ('525', '智慧城市与三维城市建模', '范红超', '[5] George Vosselman and Hans-Gerd Maas 2010: Airborne and terrestrial Laser Scanning. CRC Press, Taylor & Francis Group. ', null, null, null);
INSERT INTO `book` VALUES ('526', '智慧城市', '付仲良', '[1]郭源生,张建国,吕晶. 智慧城市的模块化构架与核心技术.国防工业出版社，2014.', null, null, null);
INSERT INTO `book` VALUES ('527', '智慧城市', '付仲良', '[2]郭理桥. 智慧城市导论. 中信出版社，2015.', null, null, null);
INSERT INTO `book` VALUES ('528', '智慧城市', '付仲良', '[3]吴余龙,艾浩军. 智慧城市. 电子工业出版社, 2011.', null, null, null);
INSERT INTO `book` VALUES ('529', '智慧城市', '付仲良', '[4]徐静,谭章禄. 智慧城市框架与实践. 电子工业出版社，2014.', null, null, null);
INSERT INTO `book` VALUES ('530', '智慧城市', '付仲良', '[5]熊璋等. 智慧城市. 科学出版社，2015.', null, null, null);
INSERT INTO `book` VALUES ('531', '生产实践D（服务学习）', '毛庆洲', '无', null, null, null);
INSERT INTO `book` VALUES ('532', '微光与红外成像技术', '毛庆洲', '[1]白廷柱,金伟其. 光电成像原理与技术[M]. 北京理工大学出版社，2006.', null, null, null);
INSERT INTO `book` VALUES ('533', '微光与红外成像技术', '毛庆洲', '[2]邸旭. 微光与红外成像技术[M]. 机械工业出版社, 2012.', null, null, null);
INSERT INTO `book` VALUES ('534', '微光与红外成像技术', '毛庆洲', '[3]邹异松，刘玉风，白廷柱. 光电成像原理[M]. 北京理工大学出版社，1997.', null, null, null);
INSERT INTO `book` VALUES ('535', '微光与红外成像技术', '毛庆洲', '[4]张敬贤，李玉丹，金伟其. 微光与红外成像技术[M].北京理工大学出版社，1995.', null, null, null);
INSERT INTO `book` VALUES ('536', '微光与红外成像技术', '毛庆洲', '[5] Vollmer M, M?llmann K P. Infrared thermal imaging : fundamentals, research and applications[M]. Latin-American Journal of Physics Education, 2013, 5(5):1431.', null, null, null);
INSERT INTO `book` VALUES ('537', '微光与红外成像技术', '毛庆洲', '[6] Lloyd J M. Thermal Imaging Systems[M]. Springer US, 1975.', null, null, null);
INSERT INTO `book` VALUES ('538', '多传感器集成与移动测量', '黄玉春', '[1]《移动测量讲义》自编教材.', null, null, null);
INSERT INTO `book` VALUES ('539', '多传感器集成与移动测量', '黄玉春', '[2]《移动测量虚拟仿真实验》自编教案.', null, null, null);
INSERT INTO `book` VALUES ('540', 'GIS可视化技术', '张文', '[1] Exploring Geovisualization. Elsevier Ltd, edited by Jason Dykes, Alan M. Maceachren, Menno-Jan Kraak, 2005.', null, null, null);
INSERT INTO `book` VALUES ('541', 'GIS可视化技术', '张文', '[2] Geographic Visualization: Concepts, Tools and Applications. John Wiley & Sons, Martin Dodge, Mary McDerby, Martin Turner, 2011.', null, null, null);
INSERT INTO `book` VALUES ('542', 'GIS可视化技术', '张文', '[3] Roger Tomlinson. Thinking About GIS”. ESRI Press, 2007. ', null, null, null);
INSERT INTO `book` VALUES ('543', 'GIS可视化技术', '张文', '[4] Geovisualization. Alphascript Publishing, Frederic P. Miller, Agnes F. Vandome, John McBrewster, 2010.', null, null, null);
INSERT INTO `book` VALUES ('544', 'GIS可视化技术', '张文', '[5] Cartography for GIS: Geovisualization and Map Communication. Papírtisk, Vít Vo?enílek, 2005. ', null, null, null);
INSERT INTO `book` VALUES ('545', 'GIS可视化技术', '张文', '[6] GIS: a visual approach(second edition). OnWord Press, Bruce E. Davis, 2001.', null, null, null);
INSERT INTO `book` VALUES ('546', '专业导论(新生研讨课)', '龚健雅', '自编讲义', null, null, null);
INSERT INTO `book` VALUES ('547', '数据挖掘与大数据分析', '康朝贵', '[1]自编教材与讲义。', null, null, null);
INSERT INTO `book` VALUES ('548', '数据挖掘与大数据分析', '康朝贵', '[2]甑峰,王波,秦萧,陈映雪,席广亮. 基于大数据的城市研究与规划方法创新. 中国建筑工业出版社, 2015.', null, null, null);
INSERT INTO `book` VALUES ('549', '数据挖掘与大数据分析', '康朝贵', '[3]何承,朱扬勇. 城市交通大数据. 上海科学技术出版社, 2015.', null, null, null);
INSERT INTO `book` VALUES ('550', '数据挖掘与大数据分析', '康朝贵', '[4] Michael Batty. The New Science of Cities. The MIT Press，2013.', null, null, null);
INSERT INTO `book` VALUES ('551', '数据挖掘与大数据分析', '康朝贵', '[5] Marc Barthelemy. The Structure and Dynamics of Cities: Urban Data Analysis and Theoretical Modeling. Cambridge University Press, 2016.', null, null, null);
INSERT INTO `book` VALUES ('565', 'bookname', '李华', '文化苦旅', null, null, null);
INSERT INTO `book` VALUES ('567', '123', '甲', '百年孤独', '爱念425', '', '.133.170.5:8888/');
INSERT INTO `book` VALUES ('568', '2', '回个话', '5325', '架', '', '');
INSERT INTO `book` VALUES ('569', '空间数据分析', '秦昆', '[4]王劲峰，空间分析，科学出版社，2006', '', '', '.133.170.5:8888/');
